"""Write manually reviewed coarse visibility labels to the local PTTI-Dev QA area.

The labels describe the displayed player at one midpoint frame per half-second
window. They are not per-frame ground truth and do not describe mask quality.
The review images are generated by ``build_anchor_visibility_sheets.py``.
"""
from __future__ import annotations

import json
import os
import sys
from datetime import datetime, timezone
from pathlib import Path

PRODUCT_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(PRODUCT_ROOT))

from backend.player_tracking_closed_loop import list_closed_loop_samples


SAMPLE_IDS = ("game_1-t60", "game_2-t60", "game_3-t60", "game_4-t30", "game_5-t60")

# One manually reviewed state for each 0.5-second midpoint image, ordered from
# 0.0–0.5 s through 9.5–10.0 s. Edge/cropped people are PARTIAL; absent people
# are OUT_OF_FRAME; do not infer visibility from a tracker mask.
LABELS = {
    "game_1-t60": {
        "NEAR_PLAYER": ["VISIBLE"] * 20,
        "FAR_PLAYER": ["VISIBLE", "VISIBLE", "VISIBLE", "VISIBLE", "PARTIAL", "PARTIAL",
                       "OUT_OF_FRAME", "OUT_OF_FRAME", "OUT_OF_FRAME", "OUT_OF_FRAME",
                       "PARTIAL", "PARTIAL", "VISIBLE", "VISIBLE", "VISIBLE", "VISIBLE",
                       "VISIBLE", "VISIBLE", "VISIBLE", "VISIBLE"],
    },
    "game_2-t60": {
        "NEAR_PLAYER": ["VISIBLE"] * 20,
        "FAR_PLAYER": ["VISIBLE"] * 10 + ["PARTIAL", "PARTIAL"] + ["OUT_OF_FRAME"] * 8,
    },
    "game_3-t60": {
        "NEAR_PLAYER": ["PARTIAL", "PARTIAL", "PARTIAL", "PARTIAL"] + ["VISIBLE"] * 16,
        "FAR_PLAYER": ["PARTIAL", "PARTIAL", "PARTIAL"] + ["VISIBLE"] * 17,
    },
    "game_4-t30": {
        "NEAR_PLAYER": ["VISIBLE"] * 20,
        "FAR_PLAYER": ["VISIBLE"] * 20,
    },
    "game_5-t60": {
        "NEAR_PLAYER": ["VISIBLE"] * 20,
        "FAR_PLAYER": ["OUT_OF_FRAME"] * 8 + ["PARTIAL"] * 6 + ["VISIBLE"] * 6,
    },
}


def main() -> None:
    local = Path(os.environ.get("LOCALAPPDATA", Path.home() / "AppData/Local"))
    output = local / "PTTI-Dev" / "vision-v2-sam2" / "runs" / "anchor-guided" / "visibility_truth_v1.json"
    samples = {row["sample_id"]: row for row in list_closed_loop_samples(local)}
    if any(sample_id not in samples for sample_id in SAMPLE_IDS):
        raise RuntimeError("EXPECTED_FIVE_CURRENT_DEV_CLIPS")

    payload = {
        "schema_version": "ptti-player-visibility-truth-v1",
        "dataset": "Extended OpenTTGames",
        "license": "CC BY-NC-SA 4.0",
        "commercial_use": False,
        "review_method": "HUMAN_REVIEWED_0_5_SECOND_WINDOWS",
        "review_basis": "local contact sheets generated from decoded frames; one midpoint frame reviewed per half-second window",
        "labels": ["VISIBLE", "PARTIAL", "OUT_OF_FRAME", "UNKNOWN"],
        "samples": {},
    }
    for sample_id in SAMPLE_IDS:
        sample = samples[sample_id]
        if sample["frames"] != 300 or sample["sample_fps"] != 30.0:
            raise RuntimeError(f"UNEXPECTED_CLIP_SHAPE:{sample_id}")
        windows = []
        for index in range(20):
            start_frame = index * 15
            end_frame = min((index + 1) * 15 - 1, sample["frames"] - 1)
            review_frame = min(sample["frames"] - 1, int((index * 0.5 + 0.25) * sample["sample_fps"] + 0.5))
            windows.append({
                "start_frame": start_frame,
                "end_frame": end_frame,
                "review_frame": review_frame,
                "start_seconds": round(index * 0.5, 3),
                "end_seconds": round(min((index + 1) * 0.5, 10.0), 3),
                "NEAR_PLAYER": LABELS[sample_id]["NEAR_PLAYER"][index],
                "FAR_PLAYER": LABELS[sample_id]["FAR_PLAYER"][index],
            })
        payload["samples"][sample_id] = {
            "match_id": sample["match_id"],
            "source_sha256": sample["clip_sha256"],
            "source_fps": sample["source_fps"],
            "sample_fps": sample["sample_fps"],
            "frames": sample["frames"],
            "windows": windows,
        }
    output.parent.mkdir(parents=True, exist_ok=True)
    temporary = output.with_suffix(".json.tmp")
    temporary.write_text(json.dumps(payload, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    temporary.replace(output)
    print(output)
    print("reviewed_windows=100")
    print("created_at_utc=" + datetime.now(timezone.utc).isoformat())


if __name__ == "__main__":
    main()
