export type FeedVideo = {key:string; kind:'LOCAL'|'OFFICIAL'; title:string; subtitle:string; thumbnail:string; duration:number|null; athletes:string[]; athleteNames:string[]; event:string; category:string; opened:string|null; source:any};
export function feedVideos(data:any):FeedVideo[]{
 const local:FeedVideo[]=(data.videos||[]).filter((v:any)=>v.availability_status==='AVAILABLE').map((v:any)=>({key:'local:'+v.video_id,kind:'LOCAL',title:v.title,subtitle:'本地录像 · 打开播放器',thumbnail:`/api/video-evidence/library/videos/${v.video_id}/thumbnail`,duration:v.duration_ms/1000,athletes:v.athlete_ids||[],athleteNames:[],event:v.match_id?data.matches.find((m:any)=>m.match_id===v.match_id)?.event_name||'本地录像':'本地录像',category:'本地录像',opened:v.last_opened_at,source:v}));
 const seen=new Set<string>();
 const official:FeedVideo[]=(data.official_videos||[]).filter((v:any)=>{if(seen.has(v.video_id))return false;seen.add(v.video_id);return v.full_match===true||!!v.source_key}).map((v:any)=>({key:'official:'+v.video_id,kind:'OFFICIAL',title:v.display_title||v.title,subtitle:v.playback_limitation|| (v.playback_status==='EMBED_VERIFIED'?'官方视频 · 在 PTTI 观看':v.watch_page_status==='PLAYBACK_VERIFIED'?'在官方平台观看':v.watch_page_status==='LOGIN_REQUIRED'?'官方平台要求登录 · 尚未验证播放':'官方来源 · 播放待核验'),thumbnail:v.thumbnail_url,duration:v.duration_seconds,athletes:v.athlete_ids||[],athleteNames:v.athlete_names||[],event:v.event_name||'赛事未核实',category:v.discipline||'UNKNOWN',opened:null,source:v}));
 return [...local,...official.sort((a,b)=>Number(!!b.source.video_source?.playback_verified)-Number(!!a.source.video_source?.playback_verified))];
}
export function filterFeed(rows:FeedVideo[],{query='',category='全部',athlete='',event='',view='home',favorites=[]}:{query?:string;category?:string;athlete?:string;event?:string;view?:string;favorites?:string[]}):FeedVideo[]{
  return rows.filter(v=>(!query||[v.title,v.event,...v.athleteNames].join(' ').toLowerCase().includes(query.trim().toLowerCase()))&&(!athlete||v.athletes.includes(athlete)||v.athleteNames.includes(athlete))&&(!event||v.event===event)&&(view!=='feedHistory'||!!v.opened)&&(view!=='feedFavorites'||favorites.includes(v.key))&&(category==='全部'||category==='完整比赛'&&v.source.video_source?.is_full_match===true||category==='关注球星'&&!!athlete||category==='本地录像'&&v.kind==='LOCAL'||category==='男单'&&v.category==='MS'||category==='女单'&&v.category==='WS'||category==='WTT'&&v.kind==='OFFICIAL'&&/WTT|Smash/i.test(v.event)||category==='世乒赛'&&/Worlds/i.test(v.event)||category==='奥运'&&/Olympic/i.test(v.event)));
}
export function officialAction(v:FeedVideo){const s=v.source.video_source;return s?.embed_permission==='ALLOWED'&&s?.playback_type==='OFFICIAL_EMBED'?'EMBED':'SOURCE_LINK';}
export function durationLabel(seconds:number|null){if(seconds==null)return '时长未核实';return `${Math.floor(seconds/60)}:${String(Math.floor(seconds)%60).padStart(2,'0')}`;}
