import {useState} from 'react';
import {allowedEmbed} from './onlinePlayers';
export default function MatchSourcePanel({match,data,onPlay,onRefresh}:{match:any;data:any;onPlay:(id:string)=>void;onRefresh:()=>Promise<void>}){
 const [provider,setProvider]=useState('BILIBILI'),[id,setId]=useState(''),[label,setLabel]=useState(''),[video,setVideo]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false);
 async function save(path:string,body:any,method:string){if(busy)return;setBusy(true);try{const r=await fetch('/api/video-evidence/library'+path,{method,headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});if(!r.ok){const d=await r.json();throw Error(d.detail||'保存失败')}await onRefresh();setNotice('关联已保存；不同录像版本的时间不自动互通。')}catch(e:any){setNotice(e.message)}finally{setBusy(false)}}
 const locals=data.videos.filter((v:any)=>v.match_id===match.match_id);
 return <section><h2>观看来源与本地复盘</h2>{(match.online_sources||[]).map((s:any)=><div key={s.source_key||s.video_id}><strong>{s.provider} · {s.title}</strong>{allowedEmbed(s)&&<iframe title={s.title} src={allowedEmbed(s)!} width="100%" height="420" allowFullScreen/>}<p><a href={s.source_url} target="_blank" rel="noopener noreferrer">在官方平台观看 ↗</a> · 完整性待核验 · 不开放 Vision</p></div>)}{locals.map((v:any)=><button disabled={v.availability_status!=='AVAILABLE'} key={v.video_id} onClick={()=>onPlay(v.video_id)}>本地复盘：{v.title}</button>)}
 <details><summary>关联本地录像以使用专业复盘</summary><p>先通过现有录像入口登记合法文件，再核对比赛。不会下载在线视频；比分始终绑定具体录像。</p><select aria-label="选择本地录像" value={video} onChange={e=>setVideo(e.target.value)}><option value="">选择已登记录像</option>{data.videos.filter((v:any)=>!v.match_id).map((v:any)=><option key={v.video_id} value={v.video_id}>{v.title}</option>)}</select><button disabled={busy||!video} onClick={()=>{if(window.confirm('已经核对录像内容和许可，确认是本场比赛？不能仅凭文件名确认。'))save(`/videos/${video}/match`,{match_id:match.match_id,user_confirmed:true},'PUT')}}>核对后确认关联</button></details>
 <details><summary>添加同场比赛观看来源</summary><select value={provider} onChange={e=>setProvider(e.target.value)}><option>BILIBILI</option><option>YOUTUBE</option></select><input aria-label="视频标识" placeholder="BV 标识 / YouTube 视频 ID" value={id} onChange={e=>setId(e.target.value)}/><input aria-label="录像版本说明" placeholder="录像版本说明" value={label} onChange={e=>setLabel(e.target.value)}/><button disabled={busy||!id||!label} onClick={()=>{if(window.confirm('已核对这是同一场比赛？仅保存来源链接，不确认版权或完整性。'))save(`/matches/${encodeURIComponent(match.match_id)}/online-sources`,{provider,source_id:id,title:label,user_confirmed_match:true},'POST')}}>保存观看来源</button></details>{notice&&<p role="status">{notice}</p>}</section>
}
