import {useEffect,useRef,useState} from 'react';
import {Card,Empty,Modal,PageHeader} from './ui';
import {savedFolderDefaults} from './libraryPlayback';
import './match-video-library.css';

const name=(a:any)=>a?.canonical_name_zh||a?.canonical_name_en||'姓名未核实';
const title=(m:any)=>`${name(m.players?.player_a)} vs ${name(m.players?.player_b)}`;
const rights=(s:string)=>s==='RESEARCH_NONCOMMERCIAL'?'研究素材 · 仅非商业使用':'已登记本机使用权限';
const roundName=(s:string)=>({"Men's Singles Final":'男子单打决赛',"Men's Singles Semifinal":'男子单打半决赛',"Men's Singles Round of 64":'男子单打64强'} as Record<string,string>)[s]||s||'轮次未核实';
const eventName=(s:string)=>({'ITTF Men’s & Women’s World Cup Macao 2026':'2026 澳门国际乒联世界杯','WTT Champions Chongqing 2025 Presented by AITO':'2025 重庆冠军赛','China Smash 2025':'2025 中国大满贯','WTT Star Contender Doha 2025':'2025 多哈球星挑战赛','Europe Smash - Sweden 2026':'2026 瑞典欧洲大满贯','WTT Finals Hong Kong 2025':'2025 香港总决赛'} as Record<string,string>)[s]||s;
async function request(path:string,body?:unknown,method='POST'){
 const r=await fetch('/api/video-evidence/library'+path,body===undefined?{}:{method,headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});
 const d=await r.json();if(!r.ok)throw new Error(typeof d.detail==='string'?d.detail:'操作未完成，请重试');return d;
}
function ScoreSearch({athleteId,matchId,onOpenScore,onPlaylist}:{athleteId?:string;matchId?:string;onOpenScore:(row:any)=>void;onPlaylist:(ids:string[])=>void}){
 const [rows,setRows]=useState<any[]>([]),[a,setA]=useState(''),[b,setB]=useState(''),[critical,setCritical]=useState(''),[status,setStatus]=useState('CONFIRMED'),[event,setEvent]=useState(''),[year,setYear]=useState(''),[selected,setSelected]=useState<string[]>([]),[error,setError]=useState('');
 useEffect(()=>{const q=new URLSearchParams();if(athleteId)q.set('athlete_id',athleteId);if(matchId)q.set('match_id',matchId);if(a!=='')q.set('score_a',a);if(b!=='')q.set('score_b',b);if(critical)q.set('critical',critical);if(status)q.set('status',status);if(event)q.set('event',event);if(year)q.set('year',year);let live=true;fetch('/api/video-evidence/scores?'+q).then(async r=>{const d=await r.json();if(!r.ok)throw Error(d.detail||'比分索引暂不可用');if(live)setRows(d)}).catch(e=>{if(live)setError(e.message)});return()=>{live=false}},[athleteId,matchId,a,b,critical,status,event,year]);
 return <Card className="score-library-search"><h2>按比分找球</h2><p>仅显示真实保存的人工比分索引；暂无记录时如实留空。</p><div className="score-query"><label>A 方比分<input type="number" min="0" value={a} onChange={e=>setA(e.target.value)}/></label><label>B 方比分<input type="number" min="0" value={b} onChange={e=>setB(e.target.value)}/></label><label>关键分<select value={critical} onChange={e=>setCritical(e.target.value)}><option value="">全部</option><option value="DEUCE">平分</option><option value="GAME_POINT">局点</option><option value="MATCH_POINT">赛点（有完整赛制信息时）</option></select></label><label>状态<select value={status} onChange={e=>setStatus(e.target.value)}><option value="CONFIRMED">人工已确认</option><option value="REVIEW_REQUIRED">待确认</option><option value="">所有状态</option></select></label><label>赛事<input value={event} onChange={e=>setEvent(e.target.value)} placeholder="赛事名称"/></label><label>年份<input type="number" min="1900" max="2200" value={year} onChange={e=>setYear(e.target.value)}/></label></div>
 {error&&<p role="alert">{error}</p>}{rows.length?<><div className="score-results">{rows.map(r=><article key={r.point_id}><label><input aria-label="选择比分片段" type="checkbox" disabled={r.verification_status!=='CONFIRMED'||r.point_start_ms==null||r.availability_status!=='AVAILABLE'} checked={selected.includes(r.point_id)} onChange={e=>setSelected(ids=>e.target.checked?[...ids,r.point_id]:ids.filter(id=>id!==r.point_id))}/></label><div><b>{r.video_title} · 第 {r.game_number} 局 · {r.score_a_before==null||r.score_b_before==null?'比分未知':`${r.score_a_before}:${r.score_b_before}`}</b><small>第 {r.point_number} 分 · {r.point_start_ms==null?'边界待确认':`${(r.point_start_ms/1000).toFixed(3)} 秒`} · {r.verification_status==='CONFIRMED'?'人工已确认':r.verification_status==='REVIEW_REQUIRED'?'待确认':'已否决'}</small>{r.availability_status!=='AVAILABLE'&&<small>原视频不可用，请重新关联</small>}</div><button disabled={r.verification_status!=='CONFIRMED'||r.point_start_ms==null||r.availability_status!=='AVAILABLE'} onClick={()=>onOpenScore(r)}>定位并播放 →</button></article>)}</div><button disabled={!selected.length} onClick={()=>onPlaylist(selected)}>连续播放所选 {selected.length} 条比分</button></>:<p>{a==='9'&&b==='9'?'当前范围尚无已索引的 9:9 片段。':'当前没有符合条件的已索引比分。'}</p>}</Card>
}

export default function MatchVideoLibrary({page,revision,onOpenVideo,onOpenScore,onScorePlaylist,navigate}:{page:string;revision:number;onOpenVideo:(id:string)=>void;onOpenScore:(row:any)=>void;onScorePlaylist:(ids:string[])=>void;navigate:(p:string)=>void}){
 const [data,setData]=useState<any>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[search,setSearch]=useState(''),[onlyPlayable,setOnlyPlayable]=useState(false);
 const [athlete,setAthlete]=useState<any>(null),[match,setMatch]=useState<any>(null),[folderOpen,setFolderOpen]=useState(false),[path,setPath]=useState(''),[sourceNote,setSourceNote]=useState(''),[permission,setPermission]=useState('USER_OWNED'),[confirmed,setConfirmed]=useState(false);
 const [scans,setScans]=useState<any[]>([]),[mapping,setMapping]=useState<Record<string,string>>({}),[existing,setExisting]=useState(''),[limit,setLimit]=useState(20),[notice,setNotice]=useState('');
 const generation=useRef(0),locked=useRef(false);
 const refresh=async()=>{const g=++generation.current;const [d,s]=await Promise.all([request(''),request('/folders')]);if(g===generation.current){setData(d);setScans(s.sort((a:any,b:any)=>b.created_at.localeCompare(a.created_at)))} };
 useEffect(()=>{setAthlete(null);setMatch(null);setSearch('');refresh().catch(e=>setError(e.message));return()=>{generation.current++}},[page,revision]);
 useEffect(()=>{if(!scans.some(s=>['RUNNING','QUEUED'].includes(s.status)))return;const timer=setInterval(()=>refresh().catch(e=>setError(e.message)),2000);return()=>clearInterval(timer)},[scans]);
 useEffect(()=>{if(!folderOpen)return;const previous=savedFolderDefaults(scans,path);if(previous){setPath(previous.path);setPermission(previous.rights_status);setSourceNote(previous.source_note);setConfirmed(false)}},[folderOpen,scans,path]);
 async function act(fn:()=>Promise<void>){if(locked.current)return;locked.current=true;setBusy(true);setError('');try{await fn()}catch(e:any){setError(e.message)}finally{locked.current=false;setBusy(false)}}
 async function pick(){await act(async()=>{const bridge=(window as any).pywebview?.api;if(!bridge?.select_video_folder){setNotice('请填写本机视频文件夹完整路径');return}const p=await bridge.select_video_folder();if(p)setPath(p)})}
 function play(id:string){request(`/videos/${id}/opened`,{},'POST').catch(()=>{});onOpenVideo(id)}
 function recentVideos(){return data.videos.filter((v:any)=>v.last_opened_at&&v.availability_status==='AVAILABLE').sort((a:any,b:any)=>b.last_opened_at.localeCompare(a.last_opened_at)).slice(0,12)}
 if(!data)return <Empty title={error?'比赛库暂时无法打开':'正在打开比赛库'} text={error||'正在读取本机录像与已收录比赛资料。'}/>;
 const current=match&&data.matches.find((m:any)=>m.match_id===match.match_id), latest=scans[0];
 const query=search.trim().toLowerCase();
 const matches=data.matches.filter((m:any)=>(!athlete||[m.player_a_id,m.player_b_id].includes(athlete.athlete_id))&&(!query||`${title(m)} ${m.event_name} ${m.event_date||''}`.toLowerCase().includes(query))&&(!onlyPlayable||m.video_source.status==='LOCAL_READY'));
 const local=data.videos.filter((v:any)=>!query||v.title.toLowerCase().includes(query));
 const videoCard=(v:any)=><Card key={v.video_id}><span className="badge">{rights(v.rights_status)}</span><h3>{v.title}</h3><p>{Math.floor(v.duration_ms/60000)} 分钟 · {v.width} × {v.height}</p><p>{v.match_id?'比赛关联已确认':'独立录像 · 未关联职业比赛'}</p>{v.availability_status==='AVAILABLE'?<button className="primary" onClick={()=>play(v.video_id)}>观看完整录像 →</button>:<p role="status">原视频离线或改变，请在文件夹索引中重新关联。</p>}</Card>;
 const matchCard=(m:any)=><Card key={m.match_id}><span className="eyebrow">{eventName(m.event_name)}</span><h3>{title(m)}</h3><p>{m.event_date||'日期未核实'} · {roundName(m.round)}</p><p>{m.final_score?`${m.final_score.player_a_games} : ${m.final_score.player_b_games}`:'结果未核实'}</p><span className="badge">{m.video_source.status==='LOCAL_READY'?'完整录像可观看':'资料已收录 · 视频待授权'}</span><div className="actions"><button onClick={()=>setMatch(m)}>打开比赛</button>{m.video_source.video_ids[0]&&<button className="primary" onClick={()=>play(m.video_source.video_ids[0])}>观看比赛</button>}</div></Card>;
 return <div className="match-video-library">
 {error&&<p className="error-banner" role="alert">{error}<button onClick={()=>setError('')}>关闭</button></p>}{notice&&<p role="status">{notice}</p>}
 <PageHeader title={current?title(current):athlete?name(athlete):page==='players'?'运动员比赛目录':page==='professionalMatches'?'比赛录像库':'先看比赛，再找关键球'} text="原始视频优先。AI 候选需要复核，比赛资料不等于视频播放权限。"><button onClick={()=>{setMatch(null);setAthlete(null);navigate('home')}}>首页</button><button className="primary" onClick={()=>setFolderOpen(true)}>选择视频文件夹</button></PageHeader>
 {page==='home'&&!current&&!athlete&&<ScoreSearch onOpenScore={onOpenScore} onPlaylist={onScorePlaylist}/>}
 {current?<>
  <Card><h2>{current.video_source.video_ids.length?'完整比赛录像':'完整视频尚未获得可播放权限'}</h2><p>{current.video_source.reason}</p>{current.video_source.video_ids.map((id:string)=>videoCard(data.videos.find((v:any)=>v.video_id===id)))}{!current.video_source.video_ids.length&&<Empty title="没有可播放的本机录像" text="官方网页只作为来源链接，不会伪装成播放器。你可为这场比赛关联自己获准使用的视频。"/>}<div className="actions"><button onClick={()=>setFolderOpen(true)}>为这场比赛关联视频</button>{current.video_source.official_url&&<a href={current.video_source.official_url} target="_blank" rel="noreferrer">打开官方来源 ↗</a>}</div>
  <label>已登记且尚未关联的录像<select value={existing} onChange={e=>setExisting(e.target.value)}><option value="">请选择并核对双方运动员</option>{data.videos.filter((v:any)=>!v.match_id).map((v:any)=><option key={v.video_id} value={v.video_id}>{v.title} · {rights(v.rights_status)}</option>)}</select></label><button disabled={busy||!existing} onClick={()=>act(async()=>{if(!window.confirm('确认这份录像确实对应本场比赛？研究样本不能冒充职业比赛。'))return;await request(`/videos/${existing}/match`,{match_id:current.match_id,user_confirmed:true},'PUT');setExisting('');await refresh()})}>确认比赛关联</button></Card>
  <ScoreSearch matchId={current.match_id} onOpenScore={onOpenScore} onPlaylist={onScorePlaylist}/><Card><h2>比赛信息与证据来源</h2><p>{eventName(current.event_name)} · {current.event_date||'日期未核实'} · {roundName(current.round)}</p><p>局分 {current.final_score?`${current.final_score.player_a_games}:${current.final_score.player_b_games}`:'未核实'} · 每局分数尚未建立索引</p>{current.sources.map((s:any)=><p key={s.source_id}><a href={s.source_url} target="_blank" rel="noreferrer">官方资料来源</a> · 收录于 {s.retrieved_at?.slice(0,10)||'时间未知'}</p>)}<p>元数据沿用已有来源快照；未获得视频的比赛不能定位比分或生成轨迹。</p><button onClick={()=>setMatch(null)}>返回比赛目录</button></Card>
 </>:<>
 <Card className="library-summary"><strong>{data.summary.matches} 场职业比赛资料</strong><strong>{data.summary.playable_professional} 场职业录像可播放</strong><strong>{data.summary.local_playable} 份本机录像可播放</strong></Card>
 <div className="actions"><label>搜索比赛、运动员、赛事<input value={search} onChange={e=>setSearch(e.target.value)} placeholder="王楚钦 / 大满贯 / 比赛名称"/></label><label className="check"><input type="checkbox" checked={onlyPlayable} onChange={e=>setOnlyPlayable(e.target.checked)}/>只看有录像的职业比赛</label></div>
  {athlete&&<><Card><p>{athlete.canonical_name_en} · 官方资料已收录</p><p>下列比赛按运动员 ID 关联，不根据视频文件名猜身份。</p><button onClick={()=>setAthlete(null)}>返回运动员目录</button></Card><ScoreSearch athleteId={athlete.athlete_id} onOpenScore={onOpenScore} onPlaylist={onScorePlaylist}/></>}
 {page==='home'&&<><h2>最近播放</h2>{recentVideos().length?<div className="library-grid">{recentVideos().map(videoCard)}</div>:<p>打开一份录像后，最近播放会保存在本机。</p>}<h2>可观看的本机完整录像</h2><div className="library-grid">{local.map(videoCard)}</div>{!local.length&&<Card><p>还没有登记本机录像。选择一次有权使用的视频文件夹，后台索引后即可观看；不需要导入 AI JSON。</p><button onClick={()=>setFolderOpen(true)}>选择我的录像文件夹</button></Card>}<h2>最近收录赛事 · 来源资料</h2><div className="library-grid">{[...new Set(data.matches.map((m:any)=>m.event_name))].map((event:any)=><Card key={event}><h3>{eventName(event)}</h3><p>已有比赛资料，录像权限按每场单独确认。</p><button onClick={()=>{setMatch(data.matches.find((m:any)=>m.event_name===event))}}>查看比赛目录</button></Card>)}</div></>}
 {(page==='players'||page==='home')&&!athlete&&<><h2>{page==='home'?'关注运动员 · 已登记目录':'职业运动员'}</h2><div className="library-grid">{data.athletes.filter((a:any)=>(page!=='home'||a.groups?.includes('TTI_PRIORITY'))&&(!query||`${name(a)} ${a.canonical_name_en}`.toLowerCase().includes(query))).map((a:any)=><Card key={a.athlete_id}><h3>{name(a)}</h3><p>{a.canonical_name_en}</p><p>{data.matches.filter((m:any)=>[m.player_a_id,m.player_b_id].includes(a.athlete_id)).length} 场已收录比赛</p><button onClick={()=>{setAthlete(a);setSearch('')}}>查看运动员比赛</button></Card>)}</div></>}
 <h2>{athlete?'该运动员的真实比赛目录':'已收录职业比赛'}</h2><div className="library-grid">{matches.map(matchCard)}</div>{!matches.length&&<Empty title="当前筛选没有比赛" text="试试其它运动员或关闭仅有录像筛选。资料与视频权限会分别显示。"/>}
 {page!=='home'&&!athlete&&<><h2>独立本机录像</h2><div className="library-grid">{local.map(videoCard)}</div></>}
 {page==='home'&&<Card><h2>关键分合集</h2>{data.collections.length?data.collections.map((c:any)=><p key={c.collection_id}>{c.name} · {c.evidence_ids.length} 个保存片段</p>):<p>观看录像后保存关键分，就可以在这里找回合集。</p>}<button onClick={()=>navigate('videoEvidence')}>打开收藏与连续复盘</button></Card>}
 </>}
 {folderOpen&&<Modal title="登记我的视频文件夹" onClose={()=>setFolderOpen(false)}><p>只扫描所选文件夹中的 MP4 / MOV / MKV / AVI；不递归、不复制视频、不运行模型。已有录像按 SHA256 识别；文件名匹配只作建议。</p><button disabled={busy} onClick={pick}>选择本机文件夹</button><label>文件夹完整路径<input value={path} onChange={e=>setPath(e.target.value)} placeholder="D:\\比赛录像"/></label><label>使用权限<select value={permission} onChange={e=>setPermission(e.target.value)}><option value="USER_OWNED">本人拥有使用权</option><option value="LICENSED">明确获准使用</option><option value="RESEARCH_NONCOMMERCIAL">研究素材 · 非商业使用</option></select></label><label>来源和许可说明<textarea value={sourceNote} onChange={e=>setSourceNote(e.target.value)}/></label><label className="check"><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/>我确认可以在本机使用文件夹中的视频</label><button disabled={busy||!confirmed||!path||!sourceNote.trim()||scans.some(s=>['RUNNING','QUEUED'].includes(s.status))} onClick={()=>act(async()=>{await request('/folders',{path,rights_status:permission,rights_confirmed:confirmed,source_note:sourceNote});setLimit(20);await refresh()})}>后台索引 / 重新扫描</button>
 {latest&&<section><h3>{({QUEUED:'等待索引',RUNNING:'正在索引',COMPLETED:'索引完成',INTERRUPTED:'索引中断',FAILED:'索引失败'} as Record<string,string>)[latest.status]}</h3><p>{latest.path} · {latest.candidates.length} 个录像</p><p>{latest.message}</p><p>{rights(latest.rights_status)} · {latest.source_note}</p>{latest.errors.map((e:string,i:number)=><p role="alert" key={i}>{e}</p>)}{latest.candidates.slice(0,limit).map((c:any)=><Card key={c.candidate_id}><h4>{c.filename}</h4><p>{Math.floor(c.media.duration/60)} 分钟 · {c.media.width} × {c.media.height} · {c.existing_video_id?'已有录像 · 不重复复制':'新录像'}</p><label>比赛关联（必须核对后确认）<select value={mapping[c.candidate_id]??current?.match_id??''} onChange={e=>setMapping(v=>({...v,[c.candidate_id]:e.target.value}))}><option value="">独立录像，不猜职业比赛</option>{data.matches.map((m:any)=><option key={m.match_id} value={m.match_id}>{title(m)} · {eventName(m.event_name)}{c.suggested_match_ids.includes(m.match_id)?' · 文件名建议':''}</option>)}</select></label><button disabled={busy||!['COMPLETED','INTERRUPTED'].includes(latest.status)} onClick={()=>act(async()=>{const mid=mapping[c.candidate_id]??current?.match_id??'';if(mid&&!window.confirm('确认录像实际对应此职业比赛？不能将研究样本绑定到不相干的运动员。'))return;const v=await request(`/folders/${latest.scan_id}/confirm`,{candidate_id:c.candidate_id,match_id:mid||null});await refresh();setFolderOpen(false);play(v.video_id)})}>确认并观看</button></Card>)}{latest.candidates.length>limit&&<button onClick={()=>setLimit(v=>v+20)}>显示更多</button>}</section>}{error&&<p role="alert">{error}</p>}</Modal>}
 </div>;
}
