import {useEffect,useRef,useState} from 'react';
import {Card} from './ui';
import {scoreSecondsDraft} from './scoreTime';
import {canPlayConfirmedScore,isUnboundedScoreObservation,observationAnchorMs} from './scoreObservation';

type Moment={point_id:string;video_asset_id:string;video_id:string;video_title:string;match_id:string|null;video_sha256:string;game_number:number;point_number:number;score_a_before:number|null;score_b_before:number|null;point_start_ms:number|null;point_end_ms:number|null;score_display_ms:number|null;field_evidence?:Record<string,{source:string;verification_status:string;value_ms?:number;source_video_sha256?:string;recorded_at?:string}>;point_winner_id:string;server_id:string;verification_status:string;updated_at:string;flags?:any;availability_status:string;notes:string;player_a_id:string;player_b_id:string};
const api=async(path:string,body?:any,method='GET')=>{const r=await fetch('/api/video-evidence/scores'+path,body===undefined?{}:{method,headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const d=await r.json();if(!r.ok)throw Error(d.detail||'比分索引操作失败');return d};
const clock=(ms:number|null)=>ms==null?'边界未确认':`${String(Math.floor(ms/3600000)).padStart(2,'0')}:${String(Math.floor(ms/60000)%60).padStart(2,'0')}:${(ms/1000%60).toFixed(3).padStart(6,'0')}`;
const blank=()=>({game_number:'1',point_number:'1',score_a_before:'',score_b_before:'',point_start_ms:'',point_end_ms:'',score_display_ms:'',field_evidence:{},point_winner_id:'UNKNOWN',server_id:'UNKNOWN',player_a_id:'UNKNOWN',player_b_id:'UNKNOWN',notes:''});
export default function ScoreNavigation({videoId,videoTitle,durationMs,currentMs,athleteIds=[],reviewTargetId=null,getCurrentTimeMs,onJump,onPlaylist}:{videoId:string;videoTitle:string;durationMs:number;currentMs:number;athleteIds?:string[];reviewTargetId?:string|null;getCurrentTimeMs:()=>number;onJump:(row:Moment,play:boolean)=>void;onPlaylist:(ids:string[])=>void}){
 const [items,setItems]=useState<Moment[]>([]),[draft,setDraft]=useState<any>(blank()),[editing,setEditing]=useState(''),[expectedUpdatedAt,setExpectedUpdatedAt]=useState(''),[refresh,setRefresh]=useState(0),[scoreA,setScoreA]=useState(''),[scoreB,setScoreB]=useState(''),[critical,setCritical]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[showAll,setShowAll]=useState(false),[history,setHistory]=useState<any[]>([]),[lastSaved,setLastSaved]=useState<Moment|null>(null);
 const [winnerFilter,setWinnerFilter]=useState('');
 const autoSelectedReview=useRef('');
 useEffect(()=>{if(!videoId)return;let live=true;const params=new URLSearchParams({video_id:videoId});if(scoreA!=='')params.set('score_a',scoreA);if(scoreB!=='')params.set('score_b',scoreB);if(critical)params.set('critical',critical);if(winnerFilter)params.set('status',winnerFilter);api('?'+params).then(v=>{if(live)setItems(v)}).catch(e=>{if(live)setError(e.message)});return()=>{live=false}},[videoId,scoreA,scoreB,critical,winnerFilter,refresh]);
 useEffect(()=>{setDraft(blank());setEditing('');setExpectedUpdatedAt('');setLastSaved(null)},[videoId]);
 useEffect(()=>{const handler=(event:KeyboardEvent)=>{if(event.altKey||event.ctrlKey||event.metaKey)return;const target=event.target as HTMLElement|null;if(target&&(['INPUT','TEXTAREA','SELECT'].includes(target.tagName)||target.isContentEditable))return;if(event.key==='['){event.preventDefault();mark('point_start_ms')}else if(event.key===']'){event.preventDefault();mark('point_end_ms')}};window.addEventListener('keydown',handler);return()=>window.removeEventListener('keydown',handler)},[currentMs]);
 const set=(key:string,value:string)=>setDraft((old:any)=>({...old,[key]:value}));
 const newEntry=()=>{setDraft(blank());setEditing('');setExpectedUpdatedAt('');setHistory([]);setLastSaved(null);setError('')};
 const save=async(status:'REVIEW_REQUIRED'|'CONFIRMED')=>{if(busy)return;setBusy(true);setError('');try{const body={...draft,video_asset_id:videoId,game_number:Number(draft.game_number),point_number:Number(draft.point_number),score_a_before:draft.score_a_before===''?null:Number(draft.score_a_before),score_b_before:draft.score_b_before===''?null:Number(draft.score_b_before),point_start_ms:draft.point_start_ms===''?null:Number(draft.point_start_ms),point_end_ms:draft.point_end_ms===''?null:Number(draft.point_end_ms),score_display_ms:draft.score_display_ms===''?null:Number(draft.score_display_ms),field_evidence:draft.field_evidence||{},verification_status:status,request_id:crypto.randomUUID(),...(editing?{expected_updated_at:expectedUpdatedAt}: {})};const saved=await api(editing?'/'+editing:'',body,editing?'PUT':'POST');setLastSaved(saved);setEditing(saved.point_id);setExpectedUpdatedAt(saved.updated_at);setDraft((old:any)=>({...old,field_evidence:saved.field_evidence||old.field_evidence}));setRefresh(x=>x+1);setHistory(await api('/'+saved.point_id+'/history'));}catch(e:any){setError(e.message)}finally{setBusy(false)}};
 function edit(row:Moment){setEditing(row.point_id);setExpectedUpdatedAt(row.updated_at);setShowAll(true);setDraft({game_number:String(row.game_number),point_number:String(row.point_number),score_a_before:row.score_a_before==null?'':String(row.score_a_before),score_b_before:row.score_b_before==null?'':String(row.score_b_before),point_start_ms:row.point_start_ms==null?'':String(row.point_start_ms),point_end_ms:row.point_end_ms==null?'':String(row.point_end_ms),score_display_ms:row.score_display_ms==null?'':String(row.score_display_ms),field_evidence:row.field_evidence||{},point_winner_id:row.point_winner_id,server_id:row.server_id,player_a_id:row.player_a_id,player_b_id:row.player_b_id,notes:row.notes||''});api('/'+row.point_id+'/history').then(setHistory).catch(e=>setError(e.message))}
 useEffect(()=>{if(!reviewTargetId){autoSelectedReview.current='';return}if(autoSelectedReview.current===reviewTargetId)return;const row=items.find(item=>item.point_id===reviewTargetId);if(!row)return;autoSelectedReview.current=reviewTargetId;edit(row)},[reviewTargetId,items]);
 const undo=async()=>{if(!editing)return;setBusy(true);try{const row=await api('/'+editing+'/undo',{},'POST');setExpectedUpdatedAt(row.updated_at);setEditing(row.point_id);setDraft({game_number:String(row.game_number),point_number:String(row.point_number),score_a_before:row.score_a_before==null?'':String(row.score_a_before),score_b_before:row.score_b_before==null?'':String(row.score_b_before),point_start_ms:row.point_start_ms==null?'':String(row.point_start_ms),point_end_ms:row.point_end_ms==null?'':String(row.point_end_ms),score_display_ms:row.score_display_ms==null?'':String(row.score_display_ms),field_evidence:row.field_evidence||{},point_winner_id:row.point_winner_id,server_id:row.server_id,player_a_id:row.player_a_id,player_b_id:row.player_b_id,notes:row.notes||''});setRefresh(x=>x+1);setHistory(await api('/'+row.point_id+'/history'))}catch(e:any){setError(e.message)}finally{setBusy(false)}};
 const remove=async()=>{if(!editing||!window.confirm('删除这条待确认草稿？已确认比分不能删除，只能修改并保留历史。'))return;setBusy(true);try{await api('/'+editing,{},'DELETE');setEditing('');setDraft(blank());setRefresh(x=>x+1)}catch(e:any){setError(e.message)}finally{setBusy(false)}};
 function setTime(key:'point_start_ms'|'point_end_ms'|'score_display_ms',value:string,source:'USER_MARKED_PLAYHEAD'|'USER_ENTERED_TIME'='USER_ENTERED_TIME'){setDraft((old:any)=>{const evidence={...old.field_evidence};if(value==='')delete evidence[key];else evidence[key]={source,verification_status:'REVIEW_REQUIRED'};return {...old,[key]:value,field_evidence:evidence}})}
 function mark(key:'point_start_ms'|'point_end_ms'|'score_display_ms'){const playerTimeMs=Math.round(getCurrentTimeMs());setTime(key,String(playerTimeMs),'USER_MARKED_PLAYHEAD')}
 function confirmTime(key:'point_start_ms'|'point_end_ms'|'score_display_ms'){setDraft((old:any)=>({...old,field_evidence:{...old.field_evidence,[key]:{source:old.field_evidence?.[key]?.source||'USER_CONFIRMED_EXISTING_VALUE',verification_status:'CONFIRMED'}}}))}
 const timeEvidenceLabel=(key:'point_start_ms'|'point_end_ms'|'score_display_ms')=>{if(draft[key]==='')return '尚未设置';const evidence=draft.field_evidence?.[key];if(!evidence)return '时间来源未单独记录 · 待复核';return `${evidence.verification_status==='CONFIRMED'?'此时间已人工确认':'此时间待复核'} · ${evidence.source==='USER_MARKED_PLAYHEAD'?'播放器标记':'手动输入'}`};
 const nextSuggestion=()=>{if(!lastSaved||!['A','B'].includes(lastSaved.point_winner_id)||lastSaved.score_a_before==null||lastSaved.score_b_before==null)return;setDraft({...blank(),game_number:String(lastSaved.game_number),point_number:String(lastSaved.point_number+1),score_a_before:String(lastSaved.score_a_before+(lastSaved.point_winner_id==='A'?1:0)),score_b_before:String(lastSaved.score_b_before+(lastSaved.point_winner_id==='B'?1:0)),player_a_id:lastSaved.player_a_id,player_b_id:lastSaved.player_b_id,server_id:'UNKNOWN'});setEditing('');setError('下一分比分仅为建议，请对照录像检查后再保存。')};
 const confirmed=items.filter(x=>x.verification_status==='CONFIRMED'&&x.point_start_ms!=null&&x.point_end_ms!=null);
 const pointText=(m:Moment)=>m.score_a_before==null||m.score_b_before==null?'比分未知':`${m.score_a_before}:${m.score_b_before}`;
 const playerOptions=['UNKNOWN',...athleteIds];
 return <Card className="score-navigation"><h2>按比分找球</h2><p>记录的是本分开始前比分。比分牌出现时间单独保存，可能晚于本分开始。点“设为当前”可用键盘快速标记起止。</p>
 {error&&<p role="alert" className="error-banner">{error}</p>}
 <div className="score-query"><label>A 方比分<input aria-label="搜索 A 方比分" type="number" min="0" value={scoreA} onChange={e=>setScoreA(e.target.value)}/></label><label>B 方比分<input aria-label="搜索 B 方比分" type="number" min="0" value={scoreB} onChange={e=>setScoreB(e.target.value)}/></label><label>关键分<select value={critical} onChange={e=>setCritical(e.target.value)}><option value="">全部</option><option value="DEUCE">平分</option><option value="GAME_POINT">局点</option><option value="MATCH_POINT">赛点（需填写局分与赛制）</option></select></label><label>记录状态<select value={winnerFilter} onChange={e=>setWinnerFilter(e.target.value)}><option value="">全部状态</option><option value="CONFIRMED">人工已确认</option><option value="REVIEW_REQUIRED">待确认</option><option value="REJECTED">已否决</option></select></label></div>
 <p className="small">当前视频：{videoTitle} · {items.length} 条符合条件 · 视频时间为源播放器时间，帧定位为近似。</p>
 {items.length? <><div className="score-results">{items.map(m=>{const anchor=observationAnchorMs(m),canOpen=m.availability_status==='AVAILABLE'&&anchor!==null,canPlay=canPlayConfirmedScore(m),observation=isUnboundedScoreObservation(m);return <article key={m.point_id}><div><b>{observation?'待确认视频观察':`第 ${m.game_number} 局 · 第 ${m.point_number} 分`} · {pointText(m)}</b><small>{observation?'观察书签 · 不计入已确认逐分记录':`${clock(m.point_start_ms)}–${clock(m.point_end_ms)} · ${m.verification_status==='CONFIRMED'?'人工已确认':m.verification_status==='REJECTED'?'已否决':'待确认'}`} · {m.availability_status==='AVAILABLE'?'视频可用':'视频不可用'}</small><small>{anchor!==null?`视频线索 ${clock(anchor)}`:'尚无可定位的观察时刻'} · {m.score_display_ms!=null?`比分牌画面 ${clock(m.score_display_ms)}`:''}</small><small>{m.field_evidence?.point_start_ms?.verification_status==='CONFIRMED'?'开始时间已单独确认':'开始时间待确认'} · {m.field_evidence?.point_end_ms?.verification_status==='CONFIRMED'?'结束时间已单独确认':'结束时间待确认'}</small><small>{m.flags?.game_point_a||m.flags?.game_point_b?'局点候选 · 尚无赛点结论':''}</small></div><div className="actions"><button disabled={!canOpen} onClick={()=>{onJump(m,false);edit(m)}}>查看视频线索</button><button disabled={!canPlay} title={canPlay?'播放完整的一分区间':'需要整条记录已确认且起止边界完整'} onClick={()=>onJump(m,true)}>播放已确认的一分</button><button onClick={()=>edit(m)}>修改记录</button></div></article>})}</div><button disabled={!confirmed.length} onClick={()=>onPlaylist(confirmed.map(x=>x.point_id))}>连续播放当前视频已确认比分（{confirmed.length}）</button></>:<p className="score-empty">{scoreA==='9'&&scoreB==='9'?'当前比赛尚无已索引的 9:9 片段。':'当前视频还没有符合筛选的比分记录。'}</p>}
 <details open={showAll} onToggle={e=>setShowAll((e.target as HTMLDetailsElement).open)}><summary>标记当前这一分 · 简洁人工流程</summary><div className="score-form">
 <label>局<input type="number" min="1" max="20" value={draft.game_number} onChange={e=>set('game_number',e.target.value)}/></label><label>本局第几分<input type="number" min="1" value={draft.point_number} onChange={e=>set('point_number',e.target.value)}/></label><label>A 方分前比分<input type="number" min="0" value={draft.score_a_before} onChange={e=>set('score_a_before',e.target.value)} placeholder="未知可空"/></label><label>B 方分前比分<input type="number" min="0" value={draft.score_b_before} onChange={e=>set('score_b_before',e.target.value)} placeholder="未知可空"/></label>
  <div className="score-time-field"><label>本分开始（秒）<input type="number" min="0" step="0.001" value={draft.point_start_ms===''?'':Number(draft.point_start_ms)/1000} onChange={e=>setTime('point_start_ms',scoreSecondsDraft(e.target.value))}/></label><div className="actions"><button accessKey="[" disabled={currentMs<0||currentMs>durationMs} onClick={()=>mark('point_start_ms')}>标记当前</button><button disabled={draft.point_start_ms===''||draft.field_evidence?.point_start_ms?.verification_status==='CONFIRMED'} onClick={()=>confirmTime('point_start_ms')}>确认此时间</button></div><small>{timeEvidenceLabel('point_start_ms')}</small></div><div className="score-time-field"><label>本分结束（秒）<input type="number" min="0" step="0.001" value={draft.point_end_ms===''?'':Number(draft.point_end_ms)/1000} onChange={e=>setTime('point_end_ms',scoreSecondsDraft(e.target.value))}/></label><div className="actions"><button accessKey="]" disabled={currentMs<0||currentMs>durationMs} onClick={()=>mark('point_end_ms')}>标记当前</button><button disabled={draft.point_end_ms===''||draft.field_evidence?.point_end_ms?.verification_status==='CONFIRMED'} onClick={()=>confirmTime('point_end_ms')}>确认此时间</button></div><small>{timeEvidenceLabel('point_end_ms')}</small></div>
  <div className="score-time-field"><label>比分牌更新时间（秒）<input type="number" min="0" step="0.001" value={draft.score_display_ms===''?'':Number(draft.score_display_ms)/1000} onChange={e=>setTime('score_display_ms',scoreSecondsDraft(e.target.value))}/></label><div className="actions"><button disabled={currentMs<0||currentMs>durationMs} onClick={()=>mark('score_display_ms')}>标记比分牌更新时间</button><button disabled={draft.score_display_ms===''||draft.field_evidence?.score_display_ms?.verification_status==='CONFIRMED'} onClick={()=>confirmTime('score_display_ms')}>确认此时间</button></div><small>{timeEvidenceLabel('score_display_ms')}</small></div><label>得分方<select value={draft.point_winner_id} onChange={e=>set('point_winner_id',e.target.value)}><option value="UNKNOWN">未知</option><option value="A">A 方</option><option value="B">B 方</option></select></label><label>发球方<select value={draft.server_id} onChange={e=>set('server_id',e.target.value)}><option value="UNKNOWN">未知</option><option value="A">A 方</option><option value="B">B 方</option></select></label>
 <label>赛前 A 已赢局数<input type="number" min="0" max="7" value={(draft as any).games_a_before||''} onChange={e=>set('games_a_before',e.target.value)}/></label><label>赛前 B 已赢局数<input type="number" min="0" max="7" value={(draft as any).games_b_before||''} onChange={e=>set('games_b_before',e.target.value)}/></label><label>比赛局制<select value={(draft as any).match_best_of||''} onChange={e=>set('match_best_of',e.target.value)}><option value="">未知</option>{[3,5,7,9].map(n=><option key={n} value={n}>{n} 局 {Math.floor(n/2)+1} 胜</option>)}</select></label>
 <label>A 方运动员 ID<select value={draft.player_a_id} onChange={e=>set('player_a_id',e.target.value)}>{playerOptions.map(x=><option key={x}>{x}</option>)}</select></label><label>B 方运动员 ID<select value={draft.player_b_id} onChange={e=>set('player_b_id',e.target.value)}>{playerOptions.map(x=><option key={x}>{x}</option>)}</select></label><label className="score-wide">备注<textarea value={draft.notes} maxLength={10000} onChange={e=>set('notes',e.target.value)}/></label>
 <div className="actions score-wide"><button disabled={busy} onClick={()=>save('REVIEW_REQUIRED')}>{editing?'保存为待确认':'保存草稿'}</button><button className="primary" disabled={busy||!draft.score_a_before||!draft.score_b_before||!draft.point_start_ms||!draft.point_end_ms} title="需要比分和完整起止边界" onClick={()=>save('CONFIRMED')}>确认并保存比分</button>{editing&&<><button disabled={busy} onClick={newEntry}>新建另一条比分记录</button><button disabled={busy||history.length<2} onClick={undo}>撤销上次修改</button><button disabled={busy||items.find(x=>x.point_id===editing)?.verification_status!=='REVIEW_REQUIRED'} onClick={remove}>删除待确认草稿</button></>}</div>
 </div></details>
 {lastSaved?.verification_status==='CONFIRMED'&&lastSaved.point_winner_id!=='UNKNOWN'&&<button onClick={nextSuggestion}>按上一分得分方建议下一分比分（需人工核对）</button>}
  {editing&&history.length>0&&<details><summary>修改历史（{history.length} 条审计记录）</summary><pre>{JSON.stringify(history.map(x=>({action:x.action,recorded_at:x.recorded_at,payload:x.payload})),null,2)}</pre></details>}
 <div className="actions"><a href={`/api/video-evidence/scores/export?format=json&video_id=${encodeURIComponent(videoId)}`}>导出 JSON</a><a href={`/api/video-evidence/scores/export?format=html&video_id=${encodeURIComponent(videoId)}`}>导出中文 HTML</a><a href={`/api/video-evidence/scores/export?format=csv&video_id=${encodeURIComponent(videoId)}`}>导出 CSV</a></div>
 </Card>
}
