import {useEffect,useRef,useState} from 'react';
import {Card,Empty,Modal,PageHeader} from './ui';
import './video-evidence.css';

type Video={video_id:string;title:string;original_path:string;duration_ms:number;fps:number;width:number;height:number;file_size:number;hash_status:string;source_sha256:string|null;availability_status:string;match_id:string|null;athlete_ids:string[]};
type Clip={evidence_id:string;video_id:string;start_ms:number;end_ms:number;representative_ms:number;tags:string[];notes:string;event_type:string;review_status:string;source:string;raw_candidate?:any};
type Collection={collection_id:string;name:string;evidence_ids:string[]};
const preset=['关键分','发球','接发球','第三板','失误','精彩回合','值得研究','待复核'];
const endpoint='/api/video-evidence';
async function api(path:string,body?:unknown,method='GET'){
 const response=await fetch(endpoint+path,body===undefined?{}:{method,headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});
 const raw=await response.text();let data;try{data=JSON.parse(raw)}catch{throw new Error('本机服务未完成操作，请重试或检查视频文件')}if(!response.ok)throw new Error(typeof data.detail==='string'?data.detail:data.detail?.message||'操作未完成，请检查输入或重新选择文件');return data;
}
const clock=(ms:number)=>{const s=Math.max(0,ms)/1000;return `${String(Math.floor(s/3600)).padStart(2,'0')}:${String(Math.floor(s/60)%60).padStart(2,'0')}:${(s%60).toFixed(3).padStart(6,'0')}`};
const initial={start_ms:0,end_ms:1000,tags:'',notes:'',event_type:'KEY_CLIP',review_status:'CONFIRMED'};
export default function VideoEvidencePlayer(){
 const [videos,setVideos]=useState<Video[]>([]),[clips,setClips]=useState<Clip[]>([]),[collections,setCollections]=useState<Collection[]>([]);
 const [videoId,setVideoId]=useState(''),[selected,setSelected]=useState<Clip|null>(null),[draft,setDraft]=useState(initial);
 const [filterVideo,setFilterVideo]=useState(''),[tag,setTag]=useState(''),[search,setSearch]=useState(''),[collection,setCollection]=useState('');
 const [checked,setChecked]=useState<string[]>([]),[collectionName,setCollectionName]=useState('');
 const [current,setCurrent]=useState(0),[jump,setJump]=useState(''),[speed,setSpeed]=useState(1),[context,setContext]=useState(2);
 const [rangePlayback,setRangePlayback]=useState(false);
 const [loopClip,setLoopClip]=useState(false),[loopPlaylist,setLoopPlaylist]=useState(false),[playlistMode,setPlaylistMode]=useState(false);
 const [notice,setNotice]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[importOpen,setImportOpen]=useState(false);
 const [sourcePath,setSourcePath]=useState(''),[title,setTitle]=useState(''),[rights,setRights]=useState(false),[sourceNote,setSourceNote]=useState('本人拍摄 / 本人拥有合法使用权');
 const [sourceRights,setSourceRights]=useState('USER_OWNED'),[matchId,setMatchId]=useState(''),[matches,setMatches]=useState<any[]>([]);
 const [relinkPath,setRelinkPath]=useState(''),[athletes,setAthletes]=useState<any[]>([]),[athleteId,setAthleteId]=useState('');
 const videoRef=useRef<HTMLVideoElement>(null),pending=useRef<{ms:number;play:boolean}|null>(null),boundaryBusy=useRef(false);
 const active=videos.find(v=>v.video_id===videoId);
 const chosenCollection=collections.find(c=>c.collection_id===collection);
 const visible=clips.filter(c=>(!filterVideo||c.video_id===filterVideo)&&(!tag||c.tags.includes(tag))&&(!search||`${c.notes} ${c.tags.join(' ')} ${videos.find(v=>v.video_id===c.video_id)?.title}`.includes(search))&&(!athleteId||videos.find(v=>v.video_id===c.video_id)?.athlete_ids.includes(athleteId))&&(!chosenCollection||chosenCollection.evidence_ids.includes(c.evidence_id))).sort((a,b)=>chosenCollection?chosenCollection.evidence_ids.indexOf(a.evidence_id)-chosenCollection.evidence_ids.indexOf(b.evidence_id):a.start_ms-b.start_ms);
 const playlist=visible.filter(c=>c.review_status!=='REJECTED');
 const playback=useRef({playlist,selected,loopClip,loopPlaylist,playlistMode,rangePlayback,context,active});
 playback.current={playlist,selected,loopClip,loopPlaylist,playlistMode,rangePlayback,context,active};
 async function refresh(){const [v,e,c]=await Promise.all([api('/videos'),api('/evidence'),api('/collections')]);setVideos(v);setClips(e);setCollections(c);return {v,e,c}}
 useEffect(()=>{refresh().catch(e=>setError(e.message));fetch('/api/professional-matches').then(r=>r.json()).then(setMatches).catch(()=>{});fetch('/api/players').then(r=>r.json()).then(setAthletes).catch(()=>{})},[]);
 useEffect(()=>{if(!videos.some(v=>v.hash_status==='PENDING'))return;const timer=setInterval(()=>api('/videos').then(setVideos).catch(()=>{}),3000);return()=>clearInterval(timer)},[videos]);
 async function work(fn:()=>Promise<void>){setBusy(true);setError('');try{await fn()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 function seek(ms:number,play=false){const v=videoRef.current;if(!v)return;if(v.readyState<1){pending.current={ms,play};return}pending.current=null;v.currentTime=Math.max(0,Math.min(ms/1000,v.duration||Infinity));if(play)v.play().catch(()=>setNotice('点击播放即可继续'));}
 function selectVideo(v:Video){setRangePlayback(false);videoRef.current?.pause();setPlaylistMode(false);setSelected(null);setVideoId(v.video_id);setDraft({...initial,end_ms:Math.min(v.duration_ms,5000)});setCurrent(0);setError('');pending.current={ms:0,play:false};}
 function openClip(c:Clip,play=false){setRangePlayback(true);const v=videos.find(v=>v.video_id===c.video_id);if(!v)return;setSelected(c);setDraft({start_ms:c.start_ms,end_ms:c.end_ms,tags:c.tags.join('，'),notes:c.notes,event_type:c.event_type,review_status:c.review_status});const start=Math.max(0,c.start_ms-context*1000);pending.current={ms:start,play};setVideoId(c.video_id);boundaryBusy.current=false;if(v.availability_status!=='AVAILABLE'){videoRef.current?.pause();setPlaylistMode(false);setError('原视频暂时离线或内容改变，请重新关联后播放');return}if(videoId===c.video_id&&videoRef.current?.readyState){pending.current=null;seek(start,play)}}
 const openRef=useRef(openClip);openRef.current=openClip;
 useEffect(()=>{let frame=0;const tick=()=>{const v=videoRef.current,s=playback.current;if(v&&!v.paused&&s.selected&&s.rangePlayback&&!boundaryBusy.current){const end=Math.min(s.active?.duration_ms||Infinity,s.selected.end_ms+s.context*1000);if(v.currentTime*1000>=end-10){boundaryBusy.current=true;v.pause();if(s.loopClip){seek(Math.max(0,s.selected.start_ms-s.context*1000),true);boundaryBusy.current=false}else if(s.playlistMode){const index=s.playlist.findIndex(c=>c.evidence_id===s.selected?.evidence_id);const next=s.playlist[index+1]||(s.loopPlaylist?s.playlist[0]:null);if(next)openRef.current(next,true);else{setPlaylistMode(false);setNotice('播放列表已看完')}}}}frame=requestAnimationFrame(tick)};frame=requestAnimationFrame(tick);return()=>cancelAnimationFrame(frame)},[]);
 async function picker(setPath:(p:string)=>void){const bridge=(window as any).pywebview?.api;if(bridge){const path=await bridge.select_evidence_video();if(path)setPath(path)}else setNotice('浏览器宿主验证：请填写本机文件完整路径；桌面版可直接选择文件。')}
 async function register(){await work(async()=>{const v=await api('/videos',{path:sourcePath,title,match_id:matchId||null,rights_status:sourceRights,rights_confirmed:rights,source_note:sourceNote},'POST');await refresh();setImportOpen(false);selectVideo(v);setNotice('视频已登记，可立即播放；原文件未复制，完整性校验在后台进行。')})}
 async function save(status=draft.review_status){if(!active)return;await work(async()=>{const body={...draft,video_id:active.video_id,tags:draft.tags.split(/[,，]/).map(t=>t.trim()).filter(Boolean),representative_ms:draft.start_ms,review_status:status};const saved=await api(selected?`/evidence/${selected.evidence_id}`:'/evidence',body,selected?'PUT':'POST');await refresh();setSelected(saved);setDraft({...draft,review_status:status});setNotice('片段、标签和笔记已保存')})}
 function newClip(){setRangePlayback(false);setSelected(null);setPlaylistMode(false);setDraft({...initial,start_ms:Math.round((videoRef.current?.currentTime||0)*1000),end_ms:Math.min(active?.duration_ms||0,Math.round((videoRef.current?.currentTime||0)*1000)+5000)});setNotice('在播放器中定位，再标记片段起止点')}
 async function createCollection(){await work(async()=>{const c=await api('/collections',{name:collectionName.trim(),evidence_ids:checked},'POST');await refresh();setCollection(c.collection_id);setCollectionName('');setNotice('收藏夹已保存，可连续播放这些片段')})}
 async function addToCollection(){if(!chosenCollection)return;await work(async()=>{await api('/collections/'+collection,{name:chosenCollection.name,evidence_ids:[...chosenCollection.evidence_ids,...checked]},'PUT');await refresh();setChecked([]);setNotice('所选片段已加入收藏夹')})}
 async function reorder(c:Clip,delta:number){if(!chosenCollection)return;const ids=[...chosenCollection.evidence_ids],i=ids.indexOf(c.evidence_id),j=i+delta;if(j<0||j>=ids.length)return;[ids[i],ids[j]]=[ids[j],ids[i]];await work(async()=>{await api('/collections/'+collection,{name:chosenCollection.name,evidence_ids:ids},'PUT');await refresh()})}
 const allTags=[...new Set([...preset,...clips.flatMap(c=>c.tags)])];
 return <div className="vep"><PageHeader title="视频复盘" text="把关键球留下来，下次从证据开始。无需启动 AI。"><button className="primary" onClick={()=>setImportOpen(true)}>导入本地比赛视频</button></PageHeader>
 <p className="vep-guide">① 选择原视频　→　② 标记片段、写笔记　→　③ 收藏同类关键球，连续复盘</p>
 {error&&<p className="error-banner" role="alert">{error}<button onClick={()=>setError('')}>关闭</button></p>}{notice&&<p className="vep-notice" role="status">{notice}</p>}{busy&&<p role="status">正在保存 / 校验，请稍候…</p>}
 {!videos.length?<Empty title="从一场你自己的比赛开始" text="引用本机视频，不复制整场文件。保存的片段始终可以回到原画面。"><button onClick={()=>setImportOpen(true)}>导入视频</button></Empty>:<div className="vep-workspace">
 <Card className="vep-library"><h2>我的比赛录像</h2><div className="vep-videos">{videos.map(v=><button key={v.video_id} className={videoId===v.video_id?'active':''} onClick={()=>selectVideo(v)}><b>{v.title}</b><small>{clock(v.duration_ms)} · {(v.file_size/1024**3).toFixed(2)} GB</small><small>{v.availability_status==='AVAILABLE'?'本机原视频':v.availability_status==='MISSING_FILE'?'视频暂时离线':'源文件已改变'}</small></button>)}</div>
 <h2>我的关键球 · {visible.length}</h2><label>收藏夹<select aria-label="收藏夹筛选" value={collection} onChange={e=>setCollection(e.target.value)}><option value="">全部片段</option>{collections.map(c=><option key={c.collection_id} value={c.collection_id}>{c.name}</option>)}</select></label>
 <label>比赛筛选<select value={filterVideo} onChange={e=>setFilterVideo(e.target.value)}><option value="">全部比赛录像</option>{videos.map(v=><option key={v.video_id} value={v.video_id}>{v.title}</option>)}</select></label>
 <label>标签筛选<select value={tag} onChange={e=>setTag(e.target.value)}><option value="">全部标签</option>{allTags.map(t=><option key={t}>{t}</option>)}</select></label>
 {videos.some(v=>v.athlete_ids.length>0)&&<label>已可靠关联的球员<select value={athleteId} onChange={e=>setAthleteId(e.target.value)}><option value="">全部球员</option>{athletes.filter(a=>videos.some(v=>v.athlete_ids.includes(a.athlete.athlete_id))).map(a=><option value={a.athlete.athlete_id} key={a.athlete.athlete_id}>{a.athlete.canonical_name_zh||a.athlete.canonical_name_en}</option>)}</select></label>}
 <label>搜索标签 / 笔记<input value={search} onChange={e=>setSearch(e.target.value)}/></label>
 <div className="vep-clips">{visible.map((c,i)=><div key={c.evidence_id} className={selected?.evidence_id===c.evidence_id?'selected':''}><label className="vep-check"><input type="checkbox" aria-label={`选择片段 ${i+1}`} checked={checked.includes(c.evidence_id)} onChange={e=>setChecked(e.target.checked?[...checked,c.evidence_id]:checked.filter(id=>id!==c.evidence_id))}/></label><button onClick={()=>{setPlaylistMode(false);openClip(c)}}><b>片段 {i+1} · {clock(c.start_ms)}</b><small>{videos.find(v=>v.video_id===c.video_id)?.title}</small><span>{c.tags.join(' · ')||'未加标签'}</span><small>{c.source==='MANUAL_CONFIRMED'?'人工标记':c.source==='AI_SUGGESTED'?'AI 建议 · 未确认':'AI 建议 · 已人工复核'}{c.review_status==='REJECTED'?' · 已拒绝':''}</small></button>{chosenCollection&&<div><button aria-label={`上移片段 ${i+1}`} onClick={()=>reorder(c,-1)}>↑</button><button aria-label={`下移片段 ${i+1}`} onClick={()=>reorder(c,1)}>↓</button></div>}</div>)}</div>
 {!visible.length&&<p>暂无符合条件的片段。先标记一段，或调整筛选。</p>}
 <label>新收藏夹名称<input value={collectionName} onChange={e=>setCollectionName(e.target.value)} placeholder="例如：接发球复盘"/></label><button disabled={busy||!collectionName.trim()} onClick={createCollection}>将所选 {checked.length} 段存为收藏夹</button>{chosenCollection&&<button disabled={busy||!checked.length} onClick={addToCollection}>加入当前收藏夹</button>}
 </Card>
 <div className="vep-center"><Card><h2>{active?.title||'选择一场比赛录像'}</h2>{active?.availability_status==='AVAILABLE'?<video ref={videoRef} className="vep-video" src={`${endpoint}/videos/${videoId}/media`} controls preload="metadata" playsInline onLoadedMetadata={()=>{const v=videoRef.current;if(v)v.playbackRate=speed;if(pending.current){const target=pending.current;pending.current=null;seek(target.ms,target.play)}}} onEnded={()=>{const s=playback.current;if(s.loopClip&&s.selected){seek(Math.max(0,s.selected.start_ms-s.context*1000),true);boundaryBusy.current=false}else if(s.playlistMode&&s.selected){const i=s.playlist.findIndex(c=>c.evidence_id===s.selected?.evidence_id);const next=s.playlist[i+1]||(s.loopPlaylist?s.playlist[0]:null);if(next)openRef.current(next,true);else{setPlaylistMode(false);setNotice("播放列表已看完")}}}} onTimeUpdate={()=>setCurrent(Math.round((videoRef.current?.currentTime||0)*1000))} onError={()=>{setPlaylistMode(false);setError('视频无法播放。检查原文件是否在线，以及 MP4 视频编码是否受 WebView2 支持。');api('/videos').then(setVideos)}}/>:<div className="vep-missing"><h3>{active?'原视频暂时不可用':'请选择视频'}</h3>{active&&<><p>片段和笔记仍保存在本机。重新关联时会验证完整 SHA256。</p><label>重新关联文件路径<input value={relinkPath} onChange={e=>setRelinkPath(e.target.value)}/></label><button onClick={()=>picker(setRelinkPath)}>选择原视频</button><button disabled={busy||!relinkPath||!active.source_sha256} onClick={()=>work(async()=>{await api(`/videos/${videoId}/relink`,{path:relinkPath},'POST');await refresh();setRelinkPath('');setNotice('文件身份一致，原有片段已恢复播放')})}>校验并重新关联</button></>}</div>}
 <div className="vep-controls"><strong aria-label="当前播放时间">{clock(current)}</strong><button onClick={()=>videoRef.current?.paused?videoRef.current.play().catch(()=>setError('请先加载可用的视频')):videoRef.current?.pause()}>播放 / 暂停</button><button onClick={()=>{setRangePlayback(false);setPlaylistMode(false)}}>查看整场视频</button><button onClick={()=>seek(current-2000)}>后退 2 秒</button><button onClick={()=>seek(current+2000)}>前进 2 秒</button><label>倍速<select aria-label="播放倍速" value={speed} onChange={e=>{const n=Number(e.target.value);setSpeed(n);if(videoRef.current)videoRef.current.playbackRate=n}}>{[.25,.5,1,1.5,2].map(n=><option value={n} key={n}>{n}×</option>)}</select></label><label>跳转（秒）<input type="number" min="0" step="0.001" value={jump} onChange={e=>setJump(e.target.value)}/></label><button disabled={!jump||!active||Number(jump)*1000>active.duration_ms||Number(jump)<0} onClick={()=>{setRangePlayback(false);setPlaylistMode(false);seek(Number(jump)*1000)}}>跳转</button></div>
 <div className="actions"><button onClick={()=>seek(current-1000/(active?.fps||30))}>近似后移一帧</button><button onClick={()=>seek(current+1000/(active?.fps||30))}>近似前移一帧</button><small>按源帧率近似移动；未承诺帧级精确定位。</small></div>
 <div className="vep-strip" aria-label="已保存片段时间轴">{active&&clips.filter(c=>c.video_id===videoId).map(c=><button title={`${clock(c.start_ms)}–${clock(c.end_ms)} ${c.tags.join(' ')}`} key={c.evidence_id} aria-label={`跳转片段 ${clock(c.start_ms)}`} style={{left:`${100*c.start_ms/active.duration_ms}%`,width:`${Math.max(.5,100*(c.end_ms-c.start_ms)/active.duration_ms)}%`}} onClick={()=>openClip(c)}/>)}<span style={{left:`${active?100*current/active.duration_ms:0}%`}}/></div>
 <details><summary>本地视频来源与身份</summary><p>{active?.original_path}</p><p>{active?.width} × {active?.height} · {active?.fps} FPS · {active?.hash_status==='VERIFIED'?'完整性已校验':'后台流式校验中，播放不需要等待'}</p><code>{active?.source_sha256||'SHA256 尚在计算'}</code></details></Card>
 <Card><h2>连续复盘</h2><p>{chosenCollection?.name||'当前筛选结果'} · {playlist.length} 个可播放片段；使用原录像时间区间，不导出额外小视频。</p><div className="actions"><button className="primary" disabled={!playlist.length} onClick={()=>{setPlaylistMode(true);openClip(playlist[0],true)}}>连续播放 {playlist.length} 个片段</button><button disabled={!selected||!playlist.length} onClick={()=>{const i=playlist.findIndex(c=>c.evidence_id===selected?.evidence_id);if(i>0)openClip(playlist[i-1],true)}}>上一片段</button><button disabled={!selected||!playlist.length} onClick={()=>{const i=playlist.findIndex(c=>c.evidence_id===selected?.evidence_id);if(i>=0&&i+1<playlist.length)openClip(playlist[i+1],true)}}>下一片段</button><button disabled={!selected} onClick={()=>selected&&openClip(selected,true)}>重看片段</button></div><div className="vep-options"><label><input type="checkbox" checked={loopClip} onChange={e=>setLoopClip(e.target.checked)}/>循环当前片段</label><label><input type="checkbox" checked={loopPlaylist} onChange={e=>setLoopPlaylist(e.target.checked)}/>循环播放列表</label><label>前后上下文<select value={context} onChange={e=>setContext(Number(e.target.value))}>{[0,1,2,3,5].map(n=><option key={n} value={n}>{n} 秒</option>)}</select></label></div>{playlistMode&&<p role="status">正在连续播放 · {playlist.findIndex(c=>c.evidence_id===selected?.evidence_id)+1} / {playlist.length}<button onClick={()=>{setPlaylistMode(false);videoRef.current?.pause()}}>停止连续播放</button></p>}</Card></div>
 <Card className="vep-editor"><h2>{selected?'片段信息':'标记一个关键片段'}</h2><span className="badge">{selected?.source==='AI_SUGGESTED'?'AI 建议 · 未确认':selected?.source==='AI_REVIEWED'?'AI 建议 · 已人工复核':'人工标记'}</span><button disabled={!active} onClick={newClip}>新建关键片段</button><label>起点（秒）<input type="number" min="0" step="0.001" value={draft.start_ms/1000} onChange={e=>setDraft({...draft,start_ms:Math.round(Number(e.target.value)*1000)})}/></label><button disabled={!active} onClick={()=>setDraft({...draft,start_ms:Math.round((videoRef.current?.currentTime||0)*1000)})}>标记当前为起点</button><label>终点（秒）<input type="number" min="0" step="0.001" value={draft.end_ms/1000} onChange={e=>setDraft({...draft,end_ms:Math.round(Number(e.target.value)*1000)})}/></label><button disabled={!active} onClick={()=>setDraft({...draft,end_ms:Math.round((videoRef.current?.currentTime||0)*1000)})}>标记当前为终点</button><label>标签（逗号分隔）<input value={draft.tags} onChange={e=>setDraft({...draft,tags:e.target.value})}/></label><div className="vep-tags">{preset.map(t=><button key={t} onClick={()=>{const values=draft.tags.split(/[,，]/).map(v=>v.trim()).filter(Boolean);setDraft({...draft,tags:values.includes(t)?values.filter(v=>v!==t).join('，'):[...values,t].join('，')})}}>{t}</button>)}</div><label>我的复盘笔记<textarea rows={5} value={draft.notes} onChange={e=>setDraft({...draft,notes:e.target.value})} placeholder="这里发生了什么？下次训练想改什么？"/></label><button className="primary" disabled={busy||!active||draft.start_ms<0||draft.end_ms<=draft.start_ms||draft.end_ms>(active?.duration_ms||0)} onClick={()=>save()}>保存片段与笔记</button>{selected?.source.startsWith('AI')&&<div className="actions"><button onClick={()=>save('CONFIRMED')}>确认并保留 AI 来源</button><button onClick={()=>save('REJECTED')}>标记误报</button></div>}{selected?.raw_candidate&&<details><summary>AI 原始证据（只读）</summary><pre>{JSON.stringify(selected.raw_candidate,null,2)}</pre></details>}{selected&&<button onClick={()=>{if(window.confirm('确定删除这个关键片段？原视频不会删除。'))work(async()=>{await api(`/evidence/${selected.evidence_id}`,{},'DELETE');await refresh();setSelected(null);setNotice('片段已删除，操作记录仍保留')})}}>删除这个片段</button>}<p className="small">标签描述你的人工复盘记录。系统不会根据标签生成战术结论。</p></Card>
 </div>}
 {importOpen&&<Modal title="导入本地比赛视频" onClose={()=>setImportOpen(false)}><p>引用原文件，不复制。请选择你拥有或获准使用的完整录像。</p><button onClick={()=>picker(setSourcePath)}>选择本机视频</button><label>原文件完整路径<input value={sourcePath} onChange={e=>setSourcePath(e.target.value)} placeholder="C:\…\我的比赛.mp4"/></label><label>比赛录像名称<input value={title} onChange={e=>setTitle(e.target.value)} placeholder="例如：周六训练赛"/></label><label>关联已登记比赛（可选）<select value={matchId} onChange={e=>setMatchId(e.target.value)}><option value="">独立录像，不猜测球员关系</option>{matches.map(m=><option key={m.match_id} value={m.match_id}>{m.event_name} · {m.players?.player_a?.canonical_name_zh||m.player_a_id} vs {m.players?.player_b?.canonical_name_zh||m.player_b_id}</option>)}</select></label><label>使用权限<select aria-label="使用权限" value={sourceRights} onChange={e=>setSourceRights(e.target.value)}><option value="USER_OWNED">本人拍摄 / 本人拥有使用权</option><option value="LICENSED">已获得使用许可</option><option value="RESEARCH_NONCOMMERCIAL">研究素材 · 仅非商业使用</option></select></label><label>来源说明<textarea aria-label="来源说明" value={sourceNote} onChange={e=>setSourceNote(e.target.value)}/></label><label className="check"><input type="checkbox" checked={rights} onChange={e=>setRights(e.target.checked)}/>我确认可以在本机使用这份录像</label><button className="primary" disabled={busy||!sourcePath||!rights||!sourceNote.trim()} onClick={register}>登记并打开视频</button>{error&&<p role="alert">{error}</p>}</Modal>}
 </div>;
}
