import {useCallback,useEffect,useRef,useState} from 'react';
import {Card,Empty,Modal,PageHeader} from './ui';
import HitCandidateReviewQueue from './HitCandidateReviewQueue';
import ScoreNavigation from './ScoreNavigation';
import FixedScoreLinks from './FixedScoreLinks';
import {canReviewCandidate,canDeleteEvidence} from './reviewQueueRequests';
import {requestedLibraryVideo} from './libraryPlayback';
import {canPlayConfirmedScore,observationAnchorMs,observationSeekMs,scoreObservationLabel} from './scoreObservation';
import './video-evidence.css';

type Video={video_id:string;title:string;original_path:string;duration_ms:number;fps:number;width:number;height:number;file_size:number;hash_status:string;source_sha256:string|null;availability_status:string;match_id:string|null;athlete_ids:string[];rights_status?:string;last_opened_at?:string};
type Clip={evidence_id:string;video_id:string;start_ms:number;end_ms:number;representative_ms:number;tags:string[];notes:string;event_type:string;review_status:string;source:string;raw_candidate?:any;suggested_side?:string;reviewer_side?:string;disposition?:string;ai_provenance?:any;review_history?:any[]};
type Collection={collection_id:string;name:string;evidence_ids:string[]};
type Point={point_id:string;video_id:string;game_number:number|null;score_a:number|null;score_b:number|null;start_ms:number;end_ms:number;tags:string[];evidence_ids:string[];notes:string};
type Batch={batch_id:string;video_id:string;status:string;processed_count:number;imported_count:number;duplicate_count:number;filtered_count:number;message:string;manifest?:any};
type AIPage={counts:Record<string,number>;total:number;offset:number;limit:number;items:Clip[]};
const preset=['关键分','发球','接发球','第三板','失误','精彩回合','值得研究'];
const endpoint='/api/video-evidence';
async function api(path:string,body?:unknown,method='GET'){
 const response=await fetch(endpoint+path,body===undefined?{}:{method,headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});
 const raw=await response.text();let data;try{data=JSON.parse(raw)}catch{throw new Error('本机服务未完成操作，请重试或检查视频文件')}if(!response.ok)throw new Error(typeof data.detail==='string'?data.detail:data.detail?.message||'操作未完成，请检查输入或重新选择文件');return data;
}
const clock=(ms:number)=>{const s=Math.max(0,ms)/1000;return `${String(Math.floor(s/3600)).padStart(2,'0')}:${String(Math.floor(s/60)%60).padStart(2,'0')}:${(s%60).toFixed(3).padStart(6,'0')}`};
const initial={start_ms:0,end_ms:1000,tags:'',notes:'',event_type:'KEY_CLIP',review_status:'CONFIRMED'};
const aiStatuses=[['UNVERIFIED','AI 待复核'],['CONFIRMED','人工已确认'],['REJECTED','已否决'],['FILTERED','算法已过滤']];

export default function VideoEvidencePlayer({initialVideoId='',initialScoreTarget=null,initialScorePlaylist=[],onInitialScoreHandled=()=>{},onInitialPlaylistHandled=()=>{},videoFirst=false,watchMode=false}:{initialVideoId?:string;initialScoreTarget?:any;initialScorePlaylist?:string[];onInitialScoreHandled?:()=>void;onInitialPlaylistHandled?:()=>void;videoFirst?:boolean;watchMode?:boolean}){
 const [showTools,setShowTools]=useState(false);
 const cinemaRef=useRef<HTMLDivElement>(null);
 async function fullscreen(){try{if(document.fullscreenElement)await document.exitFullscreen();else await cinemaRef.current?.requestFullscreen()}catch{setError('当前窗口暂不支持全屏，请使用窗口最大化')}}
 useEffect(()=>{if(initialScoreTarget)setShowTools(true)},[initialScoreTarget]);
 const appliedVideo=useRef('');
 const appliedScore=useRef('');
 const [videos,setVideos]=useState<Video[]>([]),[clips,setClips]=useState<Clip[]>([]),[collections,setCollections]=useState<Collection[]>([]),[points,setPoints]=useState<Point[]>([]);
 const [videoId,setVideoId]=useState(initialVideoId),[selected,setSelected]=useState<Clip|null>(null),[draft,setDraft]=useState(initial);
 const [filterVideo,setFilterVideo]=useState(''),[tag,setTag]=useState(''),[search,setSearch]=useState(''),[collection,setCollection]=useState('');
 const [checked,setChecked]=useState<string[]>([]),[collectionName,setCollectionName]=useState('');
 const [current,setCurrent]=useState(0),[jump,setJump]=useState(''),[speed,setSpeed]=useState(1),[context,setContext]=useState(2);
 const [playlistOverride,setPlaylistOverride]=useState<string[]|null>(null),[rangePlayback,setRangePlayback]=useState(false),[loopClip,setLoopClip]=useState(false),[loopPlaylist,setLoopPlaylist]=useState(false),[playlistMode,setPlaylistMode]=useState(false);
 const [notice,setNotice]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[importOpen,setImportOpen]=useState(false),[scoreReviewContext,setScoreReviewContext]=useState<any|null>(null);
 const [sourcePath,setSourcePath]=useState(''),[title,setTitle]=useState(''),[rights,setRights]=useState(false),[sourceNote,setSourceNote]=useState('本人拍摄 / 本人拥有合法使用权');
 const [sourceRights,setSourceRights]=useState('USER_OWNED'),[matchId,setMatchId]=useState(''),[matches,setMatches]=useState<any[]>([]);
 const [relinkPath,setRelinkPath]=useState(''),[athletes,setAthletes]=useState<any[]>([]),[athleteId,setAthleteId]=useState('');
 const [packagePath,setPackagePath]=useState(''),[aiStatus,setAiStatus]=useState('UNVERIFIED'),[aiPage,setAiPage]=useState<AIPage>({counts:{},total:0,offset:0,limit:50,items:[]}),[batches,setBatches]=useState<Batch[]>([]),[reviewSide,setReviewSide]=useState('UNKNOWN'),[reviewStamp,setReviewStamp]=useState(0),[reviewRefreshKey,setReviewRefreshKey]=useState(0),[lastReviewedId,setLastReviewedId]=useState('');
 const [pointGame,setPointGame]=useState(''),[pointA,setPointA]=useState(''),[pointB,setPointB]=useState(''),[pointStart,setPointStart]=useState(0),[pointEnd,setPointEnd]=useState(1000),[pointTags,setPointTags]=useState(''),[pointNotes,setPointNotes]=useState(''),[pointEditing,setPointEditing]=useState(''),[pointEvidence,setPointEvidence]=useState<string[]>([]);
 const videoRef=useRef<HTMLVideoElement>(null),pending=useRef<{ms:number;play:boolean}|null>(null),boundaryBusy=useRef(false),previewEndMs=useRef<number|null>(null),previewEndNotice=useRef('前后 0.5 秒预览结束'),workPending=useRef(false);
 const recentVideo=videos.filter(v=>v.availability_status==='AVAILABLE'&&v.last_opened_at).sort((a,b)=>(b.last_opened_at||'').localeCompare(a.last_opened_at||''))[0];
 const active=videos.find(v=>v.video_id===videoId),chosenCollection=collections.find(c=>c.collection_id===collection);
 const visible=clips.filter(c=>(!filterVideo||c.video_id===filterVideo)&&(!tag||c.tags.includes(tag))&&(!search||`${c.notes} ${c.tags.join(' ')} ${videos.find(v=>v.video_id===c.video_id)?.title}`.includes(search))&&(!athleteId||videos.find(v=>v.video_id===c.video_id)?.athlete_ids.includes(athleteId))&&(!chosenCollection||chosenCollection.evidence_ids.includes(c.evidence_id))).sort((a,b)=>chosenCollection?chosenCollection.evidence_ids.indexOf(a.evidence_id)-chosenCollection.evidence_ids.indexOf(b.evidence_id):a.start_ms-b.start_ms);
 const playlist=playlistOverride?playlistOverride.map(id=>clips.find(c=>c.evidence_id===id)).filter((c):c is Clip=>Boolean(c)):visible.filter(c=>c.review_status!=='REJECTED');
 const playback=useRef({playlist,selected,loopClip,loopPlaylist,playlistMode,rangePlayback,context,active});playback.current={playlist,selected,loopClip,loopPlaylist,playlistMode,rangePlayback,context,active};
 const loadAI=useCallback(async(id:string,status=aiStatus,offset=0)=>{if(!id){setAiPage({counts:{},total:0,offset:0,limit:50,items:[]});setBatches([]);return}const [page,allBatches]=await Promise.all([api(`/ai-suggestions?video_id=${encodeURIComponent(id)}&status=${status}&offset=${offset}&limit=50`),api(`/imports?video_id=${encodeURIComponent(id)}`)]);setAiPage(page);setBatches(allBatches)},[aiStatus]);
 const refresh=useCallback(async()=>{const [v,e,c,p]=await Promise.all([api('/videos'),api('/evidence'),api('/collections'),api(`/points${videoId?`?video_id=${encodeURIComponent(videoId)}`:''}`)]);setVideos(v);setClips(e);setCollections(c);setPoints(p);if(videoId)await loadAI(videoId);return {v,e,c,p}},[videoId,loadAI]);
 useEffect(()=>{refresh().catch(e=>setError(e.message));fetch('/api/professional-matches').then(r=>r.json()).then(setMatches).catch(()=>{});fetch('/api/players').then(r=>r.json()).then(setAthletes).catch(()=>{})},[]);
 useEffect(()=>{loadAI(videoId,aiStatus,aiPage.offset).catch(e=>setError(e.message))},[videoId,aiStatus,aiPage.offset]);
 useEffect(()=>{if(!videos.some(v=>v.hash_status==='PENDING'))return;const timer=setInterval(()=>api('/videos').then(setVideos).catch(()=>{}),3000);return()=>clearInterval(timer)},[videos]);
 useEffect(()=>{if(!batches.some(b=>b.status==='RUNNING'))return;const timer=setInterval(()=>loadAI(videoId,aiStatus,aiPage.offset).catch(()=>{}),1000);return()=>clearInterval(timer)},[batches,videoId,aiStatus,aiPage.offset,loadAI]);
 useEffect(()=>{const v=videoRef.current;return()=>{if(v){v.pause();v.removeAttribute('src');v.load()}}},[Boolean(active),active?.availability_status]);
 async function work(fn:()=>Promise<void>):Promise<boolean>{if(workPending.current)return false;workPending.current=true;setBusy(true);setError('');try{await fn();return true}catch(e){setError((e as Error).message);return false}finally{workPending.current=false;setBusy(false)}}
 function seek(ms:number,play=false){const v=videoRef.current;if(!v)return;if(v.readyState<1){pending.current={ms,play};return}pending.current=null;v.currentTime=Math.max(0,Math.min(ms/1000,v.duration||Infinity));if(play)v.play().catch(()=>setNotice('点击播放即可继续'))}
 function selectVideo(v:Video){previewEndMs.current=null;boundaryBusy.current=false;setRangePlayback(false);videoRef.current?.pause();setPlaylistMode(false);setSelected(null);setScoreReviewContext(null);setVideoId(v.video_id);setDraft({...initial,end_ms:Math.min(v.duration_ms,5000)});setCurrent(0);setError('');setPointStart(0);setPointEnd(Math.min(v.duration_ms,1000));pending.current={ms:0,play:false}}
 useEffect(()=>{const v=requestedLibraryVideo(videos,initialVideoId,appliedVideo.current);if(v){appliedVideo.current=initialVideoId;selectVideo(v)}},[initialVideoId,videos]);
 useEffect(()=>{if(!initialScoreTarget){appliedScore.current='';return}const v=videos.find(item=>item.video_id===initialScoreTarget.video_id);if(!v||appliedScore.current===initialScoreTarget.point_id)return;appliedScore.current=initialScoreTarget.point_id;jumpToScore(initialScoreTarget,Boolean(initialScoreTarget._playConfirmedPoint));onInitialScoreHandled()},[initialScoreTarget,videos]);
 function openClip(c:Clip,play=false){previewEndMs.current=null;boundaryBusy.current=false;setRangePlayback(true);setScoreReviewContext(null);const v=videos.find(v=>v.video_id===c.video_id);if(!v)return;setSelected(c);setDraft({start_ms:c.start_ms,end_ms:c.end_ms,tags:c.tags.join('，'),notes:c.notes,event_type:c.event_type,review_status:c.review_status});setReviewStamp(c.representative_ms);setReviewSide(c.reviewer_side||c.suggested_side||'UNKNOWN');const start=Math.max(0,c.start_ms-context*1000);pending.current={ms:start,play};setVideoId(c.video_id);if(v.availability_status!=='AVAILABLE'){videoRef.current?.pause();setPlaylistMode(false);setError('原视频暂时离线或内容改变，请重新关联后播放');return}if(videoId===c.video_id&&videoRef.current?.readyState){pending.current=null;seek(start,play)}}
 const openRef=useRef(openClip);openRef.current=openClip;
 const pendingScorePlaylist=useRef<string[]>([]);
 useEffect(()=>{if(!pendingScorePlaylist.current.length)return;const ready=pendingScorePlaylist.current.every(id=>clips.some(c=>c.evidence_id===id));if(!ready)return;const ids=pendingScorePlaylist.current;pendingScorePlaylist.current=[];setPlaylistOverride(ids);setPlaylistMode(true);const first=ids.map(id=>clips.find(c=>c.evidence_id===id)).find(Boolean);if(first)openRef.current(first,true)},[clips]);
 const externalPlaylistApplied=useRef('');
 useEffect(()=>{if(!initialScorePlaylist.length){externalPlaylistApplied.current='';return}const key=initialScorePlaylist.join('|');if(externalPlaylistApplied.current===key||!initialScorePlaylist.every(id=>clips.some(c=>c.evidence_id===id)))return;externalPlaylistApplied.current=key;setPlaylistOverride(initialScorePlaylist);setPlaylistMode(true);const first=initialScorePlaylist.map(id=>clips.find(c=>c.evidence_id===id)).find(Boolean);if(first)openRef.current(first,true);onInitialPlaylistHandled()},[initialScorePlaylist,clips]);
 async function startScorePlaylist(ids:string[]){await work(async()=>{const result=await api('/scores/playlist',ids,'POST');pendingScorePlaylist.current=result.evidence_ids;setCollection('');setFilterVideo('');setTag('');setSearch('');setAthleteId('');setPlaylistMode(false);const all=await api('/evidence');setClips(all);setNotice(`已将 ${result.evidence_ids.length} 条人工确认比分加入连续复盘`)})}
 function jumpToScore(row:any,play:boolean){const video=videos.find(item=>item.video_id===row.video_id);if(!video)return;if(video.availability_status!=='AVAILABLE'||!row.video_sha256||row.video_sha256!==video.source_sha256){setError('原视频不可用或 SHA256 与这条记录不一致，无法定位。');return}if(play&&!canPlayConfirmedScore(row)){setError('只有人工确认且起止完整的比分才能播放单分片段。');return}const anchor=play?row.point_start_ms:observationAnchorMs(row);const at=play?observationSeekMs({...row,score_display_ms:null}):observationSeekMs(row);if(anchor==null||at==null){setError('这条记录尚未保存可定位的视频观察时间。');return}previewEndMs.current=play?row.point_end_ms:null;previewEndNotice.current=play?'本分片段播放完成':'观察线索预览结束';boundaryBusy.current=false;setRangePlayback(false);setPlaylistMode(false);setScoreReviewContext(play?null:row);if(!play)videoRef.current?.pause();if(videoId!==video.video_id){selectVideo(video);setScoreReviewContext(play?null:row);if(play){previewEndMs.current=row.point_end_ms;previewEndNotice.current='本分片段播放完成'}pending.current={ms:at,play}}else seek(at,play);setNotice(play?`${video.title} · 第 ${row.game_number} 局 · ${row.score_a_before??'?'}:${row.score_b_before??'?'} · 已确认片段`:`待确认观察记录 · ${video.title} · 观察时刻 ${clock(anchor)} · 从前 1.5 秒开始，可慢放和手动拖动`)}
 function enforcePlaybackBoundary(){const v=videoRef.current,s=playback.current;if(!v||v.paused||boundaryBusy.current)return;const explicitEnd=previewEndMs.current;const end=explicitEnd??(s.selected&&s.rangePlayback?Math.min(s.active?.duration_ms||Infinity,s.selected.end_ms+s.context*1000):null);if(end==null||v.currentTime*1000<end-35)return;boundaryBusy.current=true;previewEndMs.current=null;v.pause();if(explicitEnd!=null){setRangePlayback(false);setPlaylistMode(false);setNotice(previewEndNotice.current);previewEndNotice.current='前后 0.5 秒预览结束';boundaryBusy.current=false;return}if(s.loopClip&&s.selected){seek(Math.max(0,s.selected.start_ms-s.context*1000),true);boundaryBusy.current=false}else if(s.playlistMode&&s.selected){const index=s.playlist.findIndex(c=>c.evidence_id===s.selected?.evidence_id);const next=s.playlist[index+1]||(s.loopPlaylist?s.playlist[0]:null);if(next)openRef.current(next,true);else{setPlaylistMode(false);setNotice('播放列表已看完');boundaryBusy.current=false}}else{setNotice('片段播放完成');boundaryBusy.current=false}}
 useEffect(()=>{let frame=0;const tick=()=>{enforcePlaybackBoundary();frame=requestAnimationFrame(tick)};frame=requestAnimationFrame(tick);return()=>cancelAnimationFrame(frame)},[]);
 function playCandidateContext(){if(!selected||!active)return;const start=Math.max(0,selected.representative_ms-500);previewEndMs.current=Math.min(active.duration_ms,selected.representative_ms+500);previewEndNotice.current='前后 0.5 秒预览结束';boundaryBusy.current=false;setRangePlayback(true);setPlaylistMode(false);setContext(.5);seek(start,true)}
 async function picker(setter:(p:string)=>void,kind:'video'|'package'='video'){const bridge=(window as any).pywebview?.api;if(bridge){const path=kind==='package'?await bridge.select_evidence_package():await bridge.select_evidence_video();if(path)setter(path)}else setNotice('浏览器宿主验证：请填写本机完整路径；Windows 桌面版可直接选择文件。')}
 async function register(){await work(async()=>{const v=await api('/videos',{path:sourcePath,title,match_id:matchId||null,rights_status:sourceRights,rights_confirmed:rights,source_note:sourceNote},'POST');await refresh();setImportOpen(false);selectVideo(v);setNotice('视频已登记，可立即播放；原文件未复制，完整性校验在后台进行。')})}
 async function saveManual(){if(!active)return;await work(async()=>{const tags=draft.tags.split(/[,，]/).map(t=>t.trim()).filter(Boolean);const body={...draft,video_id:active.video_id,tags,representative_ms:draft.start_ms,review_status:draft.review_status};const saved=await api(selected?`/evidence/${selected.evidence_id}`:'/evidence',body,selected?'PUT':'POST');await refresh();setSelected(saved);if(tags.includes('关键分'))await addCritical(saved.evidence_id);setNotice('人工片段、标签和笔记已保存')})}
 async function reviewAI(decision:'CONFIRMED'|'REJECTED'):Promise<boolean>{if(!selected)return false;return work(async()=>{const tags=draft.tags.split(/[,，]/).map(t=>t.trim()).filter(Boolean);const saved=await api(`/evidence/${selected.evidence_id}/review`,{decision,representative_ms:reviewStamp,start_ms:draft.start_ms,end_ms:draft.end_ms,reviewer_side:reviewSide,tags,notes:draft.notes},'POST');await refresh();setSelected(saved);setLastReviewedId(saved.evidence_id);setReviewRefreshKey(value=>value+1);if(decision==='CONFIRMED'&&tags.includes('关键分'))await addCritical(saved.evidence_id);setNotice(decision==='CONFIRMED'?'已保存人工确认，原始 AI 建议和修改记录仍保留。':'已否决；原始 AI 建议与否决记录仍保留。')})}
 async function addCritical(evidenceId:string){const currentCollections=await api('/collections') as Collection[];const existing=currentCollections.find(c=>c.name==='关键分复盘');if(existing){await api(`/collections/${existing.collection_id}`,{name:existing.name,evidence_ids:[...new Set([...existing.evidence_ids,evidenceId])]},'PUT')}else{await api('/collections',{name:'关键分复盘',evidence_ids:[evidenceId]},'POST')}await refresh()}
 async function importPackage(){if(!active||!packagePath)return;await work(async()=>{await api('/imports',{video_id:active.video_id,path:packagePath},'POST');await loadAI(active.video_id,aiStatus,0);setAiPage(p=>({...p,offset:0}));setNotice('冻结候选包已登记；正在流式导入，候选不会自动确认为事实。')})}
 async function createCollection(){await work(async()=>{const c=await api('/collections',{name:collectionName.trim(),evidence_ids:checked},'POST');await refresh();setCollection(c.collection_id);setCollectionName('');setNotice('专题已保存，可跨比赛连续播放')})}
 async function addToCollection(){if(!chosenCollection)return;await work(async()=>{await api('/collections/'+collection,{name:chosenCollection.name,evidence_ids:[...new Set([...chosenCollection.evidence_ids,...checked])]},'PUT');await refresh();setChecked([]);setNotice('所选片段已加入专题')})}
 async function reorder(c:Clip,delta:number){if(!chosenCollection)return;const ids=[...chosenCollection.evidence_ids],i=ids.indexOf(c.evidence_id),j=i+delta;if(j<0||j>=ids.length)return;[ids[i],ids[j]]=[ids[j],ids[i]];await work(async()=>{await api('/collections/'+collection,{name:chosenCollection.name,evidence_ids:ids},'PUT');await refresh()})}
 async function savePoint(){if(!active)return;await work(async()=>{const tags=pointTags.split(/[,，]/).map(t=>t.trim()).filter(Boolean);const point=await api(pointEditing?`/points/${pointEditing}`:'/points',{video_id:active.video_id,game_number:pointGame?Number(pointGame):null,score_a:pointA===''?null:Number(pointA),score_b:pointB===''?null:Number(pointB),start_ms:pointStart,end_ms:pointEnd,tags,evidence_ids:pointEvidence,notes:pointNotes},pointEditing?'PUT':'POST');await refresh();setPointEditing(point.point_id);if(tags.includes('关键分')){for(const id of pointEvidence)await addCritical(id)}setNotice('人工逐分记录已保存；比分和局数仅按你的输入记录。')})}
 function editPoint(point:Point){setPointEditing(point.point_id);setPointGame(point.game_number?String(point.game_number):'');setPointA(point.score_a==null?'':String(point.score_a));setPointB(point.score_b==null?'':String(point.score_b));setPointStart(point.start_ms);setPointEnd(point.end_ms);setPointTags(point.tags.join('，'));setPointNotes(point.notes);setPointEvidence(point.evidence_ids);seek(point.start_ms)}
 function newClip(){setRangePlayback(false);setSelected(null);setScoreReviewContext(null);setPlaylistMode(false);setDraft({...initial,start_ms:Math.round((videoRef.current?.currentTime||0)*1000),end_ms:Math.min(active?.duration_ms||0,Math.round((videoRef.current?.currentTime||0)*1000)+5000)});setNotice('在播放器中定位，再标记片段起止点')}
 const allTags=[...new Set([...preset,...clips.flatMap(c=>c.tags)])];
 const activeBatch=batches.find(b=>b.status==='RUNNING');
 const toggleTag=(value:string)=>{const values=draft.tags.split(/[,，]/).map(v=>v.trim()).filter(Boolean);setDraft({...draft,tags:values.includes(value)?values.filter(v=>v!==value).join('，'):[...values,value].join('，')})};

 return <div ref={cinemaRef} className={watchMode?`vep cinema-workspace ${showTools?"cinema-analysis":"vep-watch"}`:"vep"}>{watchMode&&<div className="actions"><button onClick={()=>setShowTools(v=>!v)}>{showTools?"关闭分析 · 返回观看":"比分复盘 / 比赛分析"}</button><button onClick={fullscreen} disabled={!active}>全屏 / 退出全屏</button><label>选择本地录像<select aria-label="影院录像" value={videoId} onChange={event=>{const v=videos.find(item=>item.video_id===event.target.value);if(v)selectVideo(v)}}><option value="">选择一场比赛</option>{videos.filter(v=>v.availability_status==='AVAILABLE').map(v=><option key={v.video_id} value={v.video_id}>{v.title}</option>)}</select></label><button disabled title="本视频尚无已核验轨迹，未运行新模型">Vision 轨迹 · 尚未生成</button></div>}<PageHeader title={watchMode?"比赛影院":"视频复盘"} text={videoFirst?'先观看原始比赛，找到关键球，再保存片段与笔记。AI 复核是可选步骤。':'AI 帮你找到值得看的时刻；每条结论都由你确认，并保留原视频证据。'}><button className="primary" onClick={()=>setImportOpen(true)}>导入本地比赛视频</button></PageHeader>
 <p className="vep-guide">{videoFirst?'① 打开完整录像 → ② 找到关键球 → ③ 保存片段与笔记 → ④ 专题连续复盘':'① 选择原视频 → ② 导入冻结 AI 候选 → ③ 播放判断并确认 → ④ 保存关键分与专题'}</p>
 {error&&<p className="error-banner" role="alert">{error}<button onClick={()=>setError('')}>关闭</button></p>}{notice&&<p className="vep-notice" role="status">{notice}</p>}{busy&&<p role="status">正在保存 / 校验，请稍候…</p>}
 {!videos.length?<Empty title="从一场你自己的比赛开始" text="引用本机视频，不复制整场文件。保存的片段始终可以回到原画面。"><button onClick={()=>setImportOpen(true)}>导入视频</button></Empty>:<div className="vep-workspace">
 <Card className="vep-library"><h2>我的比赛录像</h2><div className="vep-videos">{videos.map(v=><button key={v.video_id} className={videoId===v.video_id?'active':''} onClick={()=>selectVideo(v)}><b>{v.title}</b><small>{clock(v.duration_ms)} · {(v.file_size/1024**3).toFixed(2)} GB</small><small>{v.rights_status==='RESEARCH_NONCOMMERCIAL'?'研究素材 · 仅非商业使用':''}</small><small>{v.availability_status==='AVAILABLE'?'本机原视频':v.availability_status==='MISSING_FILE'?'视频暂时离线':'源文件已改变'}</small></button>)}</div>
 {active&&<details className="vep-ai-panel" open={!videoFirst}><summary>AI 候选复核 · 可选</summary><h2>AI 证据桥</h2><p>只导入本地冻结结果，不会启动视觉模型。候选匹配必须通过原视频 SHA256。</p><label>冻结结果包（JSONL）<input value={packagePath} onChange={e=>setPackagePath(e.target.value)} placeholder="选择 game_1–3 冻结结果包"/></label><button onClick={()=>picker(setPackagePath,'package')}>选择结果包</button><button className="primary" disabled={busy||!packagePath||active.hash_status!=='VERIFIED'||active.availability_status!=='AVAILABLE'} onClick={importPackage}>校验并导入候选</button><small>{active.hash_status==='VERIFIED'?`原视频 SHA256 已校验：${active.source_sha256?.slice(0,16)}…`:'等待原视频 SHA256 校验完成'}</small>
 {batches.map(batch=><div className="vep-import-progress" key={batch.batch_id}><b>候选包导入 · {batch.status}</b><small>{batch.message} · 已检查 {batch.processed_count} 条，新增可复核 {batch.imported_count} 条，重复跳过 {batch.duplicate_count} 条，算法过滤 {batch.filtered_count} 条</small>{batch.status==='RUNNING'&&<button onClick={()=>work(async()=>{await api(`/imports/${batch.batch_id}/cancel`,{},'POST');await loadAI(videoId)})}>暂停</button>}{['PAUSED','FAILED'].includes(batch.status)&&<button onClick={()=>work(async()=>{await api(`/imports/${batch.batch_id}/resume`,{},'POST');await loadAI(videoId)})}>恢复导入</button>}</div>)}
 <HitCandidateReviewQueue videoId={videoId} selectedId={selected?.evidence_id} refreshKey={`${reviewRefreshKey}:${batches.map(batch=>`${batch.batch_id}:${batch.status}:${batch.processed_count}`).join('|')}`} reviewVersion={reviewRefreshKey} reviewedId={lastReviewedId} busy={busy} onSelect={(candidate,play=true)=>{setPlaylistMode(false);openClip(candidate as Clip,play)}} onReview={reviewAI}/>
 </details>}
 <h2>我的复盘片段 · {visible.length}</h2><label>专题<select aria-label="专题筛选" value={collection} onChange={e=>setCollection(e.target.value)}><option value="">全部片段</option>{collections.map(c=><option key={c.collection_id} value={c.collection_id}>{c.name}</option>)}</select></label>
 <label>比赛筛选<select value={filterVideo} onChange={e=>setFilterVideo(e.target.value)}><option value="">全部比赛录像</option>{videos.map(v=><option key={v.video_id} value={v.video_id}>{v.title}</option>)}</select></label><label>标签筛选<select value={tag} onChange={e=>setTag(e.target.value)}><option value="">全部标签</option>{allTags.map(t=><option key={t}>{t}</option>)}</select></label>
 {videos.some(v=>v.athlete_ids.length>0)&&<label>已可靠关联的球员<select value={athleteId} onChange={e=>setAthleteId(e.target.value)}><option value="">全部球员</option>{athletes.filter(a=>videos.some(v=>v.athlete_ids.includes(a.athlete.athlete_id))).map(a=><option value={a.athlete.athlete_id} key={a.athlete.athlete_id}>{a.athlete.canonical_name_zh||a.athlete.canonical_name_en}</option>)}</select></label>}
 <label>搜索标签 / 笔记<input value={search} onChange={e=>setSearch(e.target.value)}/></label><div className="vep-clips">{visible.map((c,i)=><div key={c.evidence_id} className={selected?.evidence_id===c.evidence_id?'selected':''}><label className="vep-check"><input type="checkbox" aria-label={`选择片段 ${i+1}`} checked={checked.includes(c.evidence_id)} onChange={e=>setChecked(e.target.checked?[...checked,c.evidence_id]:checked.filter(id=>id!==c.evidence_id))}/></label><button onClick={()=>{setPlaylistMode(false);openClip(c)}}><b>片段 {i+1} · {clock(c.start_ms)}</b><small>{videos.find(v=>v.video_id===c.video_id)?.title}</small><span>{c.tags.join(' · ')||'未加标签'}</span><small>{c.source==='MANUAL_CONFIRMED'?'人工标记':'AI 建议 · 人工已确认'}</small></button>{chosenCollection&&<div><button aria-label={`上移片段 ${i+1}`} onClick={()=>reorder(c,-1)}>↑</button><button aria-label={`下移片段 ${i+1}`} onClick={()=>reorder(c,1)}>↓</button></div>}</div>)}</div>
 {!visible.length&&<p>暂无符合条件的片段。先标记一段，或调整筛选。</p>}
 <label>新专题名称<input value={collectionName} onChange={e=>setCollectionName(e.target.value)} placeholder="例如：关键分复盘、接发球复盘"/></label><button disabled={busy||!collectionName.trim()} onClick={createCollection}>将所选 {checked.length} 段存为专题</button>{chosenCollection&&<button disabled={busy||!checked.length} onClick={addToCollection}>加入当前专题</button>}
 </Card>
 <div className="vep-center"><Card><h2>{active?.title||'选择一场比赛录像'}</h2>{active?.availability_status==='AVAILABLE'?<video ref={videoRef} className="vep-video" src={`${endpoint}/videos/${videoId}/media`} controls preload="metadata" playsInline onLoadedMetadata={()=>{const v=videoRef.current;if(v)v.playbackRate=speed;if(pending.current){const target=pending.current;pending.current=null;seek(target.ms,target.play)}}} onEnded={()=>{if(previewEndMs.current!=null){previewEndMs.current=null;setRangePlayback(false);setNotice('前后 0.5 秒预览结束');return}const s=playback.current;if(s.loopClip&&s.selected){seek(Math.max(0,s.selected.start_ms-s.context*1000),true);boundaryBusy.current=false}else if(s.playlistMode&&s.selected){const i=s.playlist.findIndex(c=>c.evidence_id===s.selected?.evidence_id);const next=s.playlist[i+1]||(s.loopPlaylist?s.playlist[0]:null);if(next)openRef.current(next,true);else{setPlaylistMode(false);setNotice('播放列表已看完')}}}} onTimeUpdate={()=>{setCurrent(Math.round((videoRef.current?.currentTime||0)*1000));enforcePlaybackBoundary()}} onError={()=>{setPlaylistMode(false);setError('视频无法播放。检查原文件是否在线，以及 MP4 视频编码是否受 WebView2 支持。');api('/videos').then(setVideos)}}/>:<div className="vep-missing"><h3>{active?'原视频暂时不可用':'打开一场比赛，开始观看'}</h3>{!active&&<><p>只播放你有权使用的录像，不自动加载在线来源。</p><button className="primary" onClick={()=>setImportOpen(true)}>打开本地视频</button>{recentVideo&&<button onClick={()=>selectVideo(recentVideo)}>继续观看 · {recentVideo.title}（从开头打开）</button>}</>}{active&&<><p>片段和笔记仍保存在本机。重新关联时会验证完整 SHA256。</p><label>重新关联文件路径<input value={relinkPath} onChange={e=>setRelinkPath(e.target.value)}/></label><button onClick={()=>picker(setRelinkPath)}>选择原视频</button><button disabled={busy||!relinkPath||!active.source_sha256} onClick={()=>work(async()=>{await api(`/videos/${videoId}/relink`,{path:relinkPath},'POST');await refresh();setRelinkPath('');setNotice('文件身份一致，原有片段已恢复播放')})}>校验并重新关联</button></>}</div>}
  {scoreReviewContext&&<aside className="score-observation-banner" role="status"><div><strong>{scoreReviewContext.verification_status==='REJECTED'?'已否决的比分画面观察':'待确认观察记录'}</strong><span>{scoreObservationLabel(scoreReviewContext)} · 观察时刻 {observationAnchorMs(scoreReviewContext)==null?'未记录':clock(observationAnchorMs(scoreReviewContext)!)}</span><small>这不是已确认的一分。可暂停、慢放、拖动并分别标记时间；记录 SHA256 {active?.source_sha256===scoreReviewContext.video_sha256?'匹配':'待核对'}。</small></div><button onClick={()=>document.querySelector('.score-navigation')?.scrollIntoView({behavior:'smooth',block:'start'})}>打开观察记录</button><button onClick={()=>setScoreReviewContext(null)}>收起</button></aside>}
  <div className="vep-controls"><strong aria-label="当前播放时间">{clock(current)}</strong><button onClick={()=>videoRef.current?.paused?videoRef.current.play().catch(()=>setError('请先加载可用的视频')):videoRef.current?.pause()}>播放 / 暂停</button><button onClick={()=>{previewEndMs.current=null;setRangePlayback(false);setPlaylistMode(false);setScoreReviewContext(null)}}>查看整场视频</button><button onClick={()=>seek(current-2000)}>后退 2 秒</button><button onClick={()=>seek(current+2000)}>前进 2 秒</button><label>倍速<select aria-label="播放倍速" value={speed} onChange={e=>{const n=Number(e.target.value);setSpeed(n);if(videoRef.current)videoRef.current.playbackRate=n}}>{[.25,.5,1,1.5,2].map(n=><option value={n} key={n}>{n}×</option>)}</select></label><label>跳转（秒）<input type="number" min="0" step="0.001" value={jump} onChange={e=>setJump(e.target.value)}/></label><button disabled={!jump||!active||Number(jump)*1000>active.duration_ms||Number(jump)<0} onClick={()=>{previewEndMs.current=null;setRangePlayback(false);setPlaylistMode(false);seek(Number(jump)*1000)}}>跳转</button></div>
 <div className="actions"><button onClick={()=>seek(current-1000/(active?.fps||30))}>近似后移一帧</button><button onClick={()=>seek(current+1000/(active?.fps||30))}>近似前移一帧</button><small>按源帧率近似移动；未承诺帧级精确定位。</small></div>
 <div className="vep-strip" aria-label="已保存片段时间轴">{active&&clips.filter(c=>c.video_id===videoId).map(c=><button title={`${clock(c.start_ms)}–${clock(c.end_ms)} ${c.tags.join(' ')}`} key={c.evidence_id} aria-label={`跳转片段 ${clock(c.start_ms)}`} style={{left:`${100*c.start_ms/active.duration_ms}%`,width:`${Math.max(.5,100*(c.end_ms-c.start_ms)/active.duration_ms)}%`}} onClick={()=>openClip(c)}/>)}<span style={{left:`${active?100*current/active.duration_ms:0}%`}}/></div>
 {watchMode&&<FixedScoreLinks videoId={active?.video_id||''} onJump={jumpToScore}/>}<details><summary>本地视频来源与身份</summary><p>{active?.original_path}</p><p>{active?.width} × {active?.height} · {active?.fps} FPS · {active?.hash_status==='VERIFIED'?'完整性已校验':'后台流式校验中，播放不需要等待'}</p><code>{active?.source_sha256||'SHA256 尚在计算'}</code></details></Card>
  <ScoreNavigation videoId={active?.video_id||''} videoTitle={active?.title||''} durationMs={active?.duration_ms||0} currentMs={current} athleteIds={active?.athlete_ids||[]} reviewTargetId={scoreReviewContext?.point_id||null} getCurrentTimeMs={()=>Math.round((videoRef.current?.currentTime||0)*1000)} onJump={jumpToScore} onPlaylist={startScorePlaylist}/>
 <Card><h2>旧版人工逐分备注</h2><p>已有旧版记录仍保留。新建比分请使用上方“按比分找球”，以记录分前比分、视频校验身份和确认状态。</p><div className="vep-points">{points.filter(point=>point.video_id===active?.video_id&&!(point as any).schema).map(point=><button key={point.point_id} onClick={()=>editPoint(point)}><b>{point.game_number?`第 ${point.game_number} 局 · `:''}{point.score_a==null||point.score_b==null?'比分未确认':`${point.score_a}:${point.score_b}`}</b><small>{clock(point.start_ms)}–{clock(point.end_ms)} · {point.tags.join(' · ')||'人工逐分记录'} · {point.evidence_ids.length} 个证据</small></button>)}</div></Card>
 <Card><h2>连续复盘</h2><p>{chosenCollection?.name||'当前筛选结果'} · {playlist.length} 个已确认或人工片段；使用原录像时间区间。</p><div className="actions"><button className="primary" disabled={!playlist.length} onClick={()=>{setPlaylistMode(true);openClip(playlist[0],true)}}>连续播放 {playlist.length} 个片段</button><button disabled={!selected||!playlist.length} onClick={()=>{const i=playlist.findIndex(c=>c.evidence_id===selected?.evidence_id);if(i>0)openClip(playlist[i-1],true)}}>上一片段</button><button disabled={!selected||!playlist.length} onClick={()=>{const i=playlist.findIndex(c=>c.evidence_id===selected?.evidence_id);if(i>=0&&i+1<playlist.length)openClip(playlist[i+1],true)}}>下一片段</button><button disabled={!selected} onClick={()=>selected&&openClip(selected,true)}>重看片段</button></div><div className="vep-options"><label><input type="checkbox" checked={loopClip} onChange={e=>setLoopClip(e.target.checked)}/>循环当前片段</label><label><input type="checkbox" checked={loopPlaylist} onChange={e=>setLoopPlaylist(e.target.checked)}/>循环播放列表</label><label>前后上下文<select value={context} onChange={e=>setContext(Number(e.target.value))}>{[0,.5,1,2,3,5].map(n=><option key={n} value={n}>{n} 秒</option>)}</select></label></div>{playlistMode&&<p role="status">正在连续播放 · {playlist.findIndex(c=>c.evidence_id===selected?.evidence_id)+1} / {playlist.length}<button onClick={()=>{setPlaylistMode(false);videoRef.current?.pause()}}>停止连续播放</button></p>}</Card></div>
 <Card className="vep-editor"><h2>{selected?(selected.source==='AI_SUGGESTION'?'复核 AI 击球候选':'片段信息'):'标记一个关键片段'}</h2><span className="badge">{selected?.source==='AI_SUGGESTION'?selected.review_status==='UNVERIFIED'?'AI 建议 · 尚未确认':selected.review_status==='FILTERED'?'算法已过滤 · 研究记录':`AI 建议 · ${selected.review_status==='REJECTED'?'已否决':'人工已确认'}`:'人工标记'}</span><button disabled={!active} onClick={newClip}>新建关键片段</button>
 {selected?.source==='AI_SUGGESTION'&&<section className="vep-ai-review"><p><b>建议时间：</b>{clock(selected.raw_candidate?.timestamp_ms??selected.representative_ms)} · <b>击球方：</b>{selected.suggested_side||'UNKNOWN'}</p><p>这是冻结模型的候选提示，不是事实。击球方未知时会保持 UNKNOWN。</p><label>人工判断击球方<select value={reviewSide} onChange={e=>setReviewSide(e.target.value)}><option value="UNKNOWN">未知</option><option value="NEAR">Near</option><option value="FAR">Far</option></select></label><label>人工时间（秒）<input type="number" min="0" step="0.001" value={reviewStamp/1000} onChange={e=>setReviewStamp(Math.round(Number(e.target.value)*1000))}/></label><button onClick={()=>setReviewStamp(current)}>使用当前播放时刻</button><button onClick={playCandidateContext}>播放前后 0.5 秒</button></section>}
 <label>片段起点（秒）<input type="number" min="0" step="0.001" value={draft.start_ms/1000} onChange={e=>setDraft({...draft,start_ms:Math.round(Number(e.target.value)*1000)})}/></label><button disabled={!active} onClick={()=>setDraft({...draft,start_ms:Math.round((videoRef.current?.currentTime||0)*1000)})}>标记当前为起点</button><label>片段终点（秒）<input type="number" min="0" step="0.001" value={draft.end_ms/1000} onChange={e=>setDraft({...draft,end_ms:Math.round(Number(e.target.value)*1000)})}/></label><button disabled={!active} onClick={()=>setDraft({...draft,end_ms:Math.round((videoRef.current?.currentTime||0)*1000)})}>标记当前为终点</button>
 <label>标签（逗号分隔）<input value={draft.tags} onChange={e=>setDraft({...draft,tags:e.target.value})}/></label><div className="vep-tags">{preset.map(t=><button key={t} onClick={()=>toggleTag(t)}>{t}</button>)}</div><label>我的复盘笔记<textarea rows={4} value={draft.notes} onChange={e=>setDraft({...draft,notes:e.target.value})} placeholder="这里发生了什么？下次训练想改什么？"/></label>
 {selected?.source==='AI_SUGGESTION'?<div className="actions"><button className="primary" disabled={busy||!canReviewCandidate(selected)||draft.start_ms<0||draft.end_ms<=draft.start_ms||draft.end_ms>(active?.duration_ms||0)} onClick={()=>reviewAI('CONFIRMED')}>{selected.review_status==='CONFIRMED'?'保存人工更正':selected.review_status==='REJECTED'?'重新确认这条候选':'确认这次击球'}</button><button disabled={busy||!canReviewCandidate(selected)} onClick={()=>reviewAI('REJECTED')}>否决为误报</button></div>:<button className="primary" disabled={busy||!active||draft.start_ms<0||draft.end_ms<=draft.start_ms||draft.end_ms>(active?.duration_ms||0)} onClick={saveManual}>保存片段与笔记</button>}
 {selected?.source==='AI_SUGGESTION'&&<p className="small">规则证据评分：{Number(selected.raw_candidate?.evidence_score??0).toFixed(3)}（不是校准概率） · 轨迹状态：{selected.raw_candidate?.ball_quality||'未知'} · 原候选 ID：{selected.raw_candidate?.event_id||'未知'} · 时间基准：{selected.ai_provenance?.timestamp_mapping?.timestamp_source==='SOURCE_PTS'?'源 PTS':selected.ai_provenance?.timestamp_mapping?.kind==='CANONICAL_SOURCE_TIMESTAMP_MS'?'源时间轴映射':'来源未标明'}</p>}
 {selected?.source==='AI_SUGGESTION'&&<details><summary>本次候选使用的证据</summary><p>以下是可用的原始规则证据。空值表示未提供，不代表不存在。</p><pre>{JSON.stringify(selected.raw_candidate?.evidence_components??selected.raw_candidate?.evidence??{ball_quality:selected.raw_candidate?.ball_quality??null,player_side:selected.suggested_side??'UNKNOWN',identity_status:selected.raw_candidate?.identity_status??null},null,2)}</pre><p>Pose（若有）是二维估计，不用于推断正手、反手或战术结论。</p></details>}
 {selected?.source==='AI_SUGGESTION'&&<details><summary>AI 来源、冻结配置与修改历史</summary><p>比赛：{selected.ai_provenance?.source_match_reference}</p><p>模型：{selected.ai_provenance?.model_version}</p><p>配置 SHA256：<code>{selected.ai_provenance?.frozen_config_sha256}</code></p><p>原视频 SHA256：<code>{selected.ai_provenance?.source_video_sha256}</code></p><p>研究素材许可：{selected.ai_provenance?.dataset_license} · 非商业使用</p><pre>{JSON.stringify(selected.review_history||[],null,2)}</pre><pre>{JSON.stringify(selected.raw_candidate,null,2)}</pre></details>}
 {selected&&selected.source!=='AI_SUGGESTION'&&<><button className="primary" disabled={busy||!active||draft.start_ms<0||draft.end_ms<=draft.start_ms||draft.end_ms>(active?.duration_ms||0)} onClick={saveManual}>保存片段与笔记</button><div className="actions"><button onClick={()=>saveManual()}>人工确认</button></div></>}
 {selected&&canDeleteEvidence(selected)&&<button onClick={()=>{if(window.confirm('确定删除这个关键片段？原视频不会删除。'))work(async()=>{await api(`/evidence/${selected.evidence_id}`,{},'DELETE');await refresh();setSelected(null);setNotice('片段已删除，操作记录仍保留')})}}>删除这个片段</button>}<p className="small">系统不会根据候选自动生成战术结论。AI 原始建议只追加人工判断，不会被覆盖。</p></Card>
 </div>}
 {importOpen&&<Modal title="导入本地比赛视频" onClose={()=>setImportOpen(false)}><p>引用原文件，不复制。请选择你拥有或获准使用的完整录像。</p><button onClick={()=>picker(setSourcePath)}>选择本机视频</button><label>原文件完整路径<input value={sourcePath} onChange={e=>setSourcePath(e.target.value)} placeholder="C:\…\我的比赛.mp4"/></label><label>比赛录像名称<input value={title} onChange={e=>setTitle(e.target.value)} placeholder="例如：周六训练赛"/></label><label>关联已登记比赛（可选）<select value={matchId} onChange={e=>setMatchId(e.target.value)}><option value="">独立录像，不猜测球员关系</option>{matches.map(m=><option key={m.match_id} value={m.match_id}>{m.event_name} · {m.players?.player_a?.canonical_name_zh||m.player_a_id} vs {m.players?.player_b?.canonical_name_zh||m.player_b_id}</option>)}</select></label><label>使用权限<select aria-label="使用权限" value={sourceRights} onChange={e=>setSourceRights(e.target.value)}><option value="USER_OWNED">本人拍摄 / 本人拥有使用权</option><option value="LICENSED">已获得使用许可</option><option value="RESEARCH_NONCOMMERCIAL">研究素材 · 仅非商业使用</option></select></label><label>来源说明<textarea aria-label="来源说明" value={sourceNote} onChange={e=>setSourceNote(e.target.value)}/></label><label className="check"><input type="checkbox" checked={rights} onChange={e=>setRights(e.target.checked)}/>我确认可以在本机使用这份录像</label><button className="primary" disabled={busy||!sourcePath||!rights||!sourceNote.trim()} onClick={register}>登记并打开视频</button>{error&&<p role="alert">{error}</p>}</Modal>}
 </div>;
}
