import {useEffect,useRef,useState} from 'react';
import {Modal} from './ui';

export default function VisionPlayer({onCinema}:{onCinema:()=>void}){
 const [opening,setOpening]=useState(false),[path,setPath]=useState(''),[note,setNote]=useState(''),[permission,setPermission]=useState(false),[busy,setBusy]=useState(false);
 const [videos,setVideos]=useState<any[]>([]),[id,setId]=useState(''),[error,setError]=useState(''),[time,setTime]=useState(0),[loaded,setLoaded]=useState(false);
 const player=useRef<HTMLVideoElement>(null);
 useEffect(()=>{let live=true;fetch('/api/video-evidence/videos').then(async r=>{if(!r.ok)throw Error('视频来源暂不可用');return r.json()}).then(rows=>{if(live)setVideos(rows.filter((v:any)=>['LICENSED_FOR_ANALYSIS','RESEARCH_NONCOMMERCIAL'].includes(v.rights_status)))}).catch(e=>{if(live)setError(e.message)});return()=>{live=false}},[]);
 const source=videos.find(v=>v.video_id===id);
 async function openSource(){setBusy(true);setError('');try{const r=await fetch('/api/video-evidence/videos',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({path,rights_status:'LICENSED_FOR_ANALYSIS',rights_confirmed:permission,source_note:note})});const v=await r.json();if(!r.ok)throw Error(typeof v.detail==='string'?v.detail:'视频无法登记，请检查来源和权限');setVideos(rows=>[...rows,v]);setId(v.video_id);setTime(0);setLoaded(false);setOpening(false)}catch(e:any){setError(e.message)}finally{setBusy(false)}}
 return <section className="vision-player"><div className="actions"><button onClick={onCinema}>返回 Cinema</button><button onClick={()=>setOpening(true)}>打开获准分析的视频</button><label>分析许可视频<select aria-label="Vision 视频来源" value={id} onChange={e=>{setId(e.target.value);setError('');setTime(0);setLoaded(false)}}><option value="">选择已获准分析的本地录像</option>{videos.map(v=><option key={v.video_id} value={v.video_id}>{v.title}{v.availability_status!=='AVAILABLE'?' · 文件不可用':''}</option>)}</select></label><span className="badge">Source Video · 原始画面</span><button disabled title="暂无与此来源 SHA256 和时间轴绑定的已验证分析数据">Analysis View · 暂不可用</button></div>
 {source?.availability_status==='AVAILABLE'?<video key={id} ref={player} controls preload="metadata" src={`/api/video-evidence/videos/${encodeURIComponent(id)}/media`} onLoadedMetadata={()=>setLoaded(true)} onTimeUpdate={e=>setTime(e.currentTarget.currentTime)} onError={()=>setError('原视频无法播放或解码，请核对文件和媒体格式')} style={{width:'100%',height:'min(70vh,calc((100vw - 48px)*9/16))',objectFit:'contain',background:'#000'}}/>:<div className="vision-source-empty">{source?'原文件已移动、缺失或改变':'选择视频以进入 Vision 播放器'}{!videos.length&&<p>当前没有已登记且明确获准分析的来源。普通观看仍可从视频首页进入。</p>}</div>}
 <div className="actions">{[.25,.5,1,2].map(rate=><button key={rate} disabled={!loaded} onClick={()=>{if(player.current)player.current.playbackRate=rate}}>{rate}×</button>)}<button disabled={!loaded} onClick={async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else await player.current?.requestFullscreen()}catch{setError('当前窗口不支持全屏，请最大化窗口')}}}>全屏</button><span>{time.toFixed(3)} s · 估算源帧 {source?Math.floor(time*source.fps):'—'}</span></div>
 {error&&<p role="alert">{error}</p>}<details><summary>来源与时间基准</summary><p>播放器 currentTime（秒）；源帧号按 FPS 估算，非逐帧 PTS 测量。Source Video 可播放不代表轨迹已验证。</p><p>SHA256：{source?.source_sha256||'尚未验证'}</p><p>权限：{source?.rights_status||'未选择'} · 分析数据：NOT_AVAILABLE</p></details>{opening&&<Modal title="打开分析许可视频" onClose={()=>setOpening(false)}><button disabled={busy} onClick={async()=>{try{const picker=(window as any).pywebview?.api?.select_evidence_video;if(picker){const selected=await picker();if(selected)setPath(selected)}}catch{setError('文件选择未完成，请重试')}}}>选择本机视频</button><label>本机视频路径<input value={path} onChange={e=>setPath(e.target.value)}/></label><label>来源与分析许可说明<input value={note} onChange={e=>setNote(e.target.value)}/></label><label className="check"><input type="checkbox" checked={permission} onChange={e=>setPermission(e.target.checked)}/>我已获得本机分析许可；持有文件不等于获得分析权</label><button disabled={busy||!permission||!path||!note.trim()} onClick={openSource}>引用原视频并打开</button><p>不复制、不上传，不运行模型。分析结果保持待验证。</p>{error&&<p role="alert">{error}</p>}</Modal>}</section>;
}
