import {useEffect,useState} from 'react';
import {Card,PageHeader} from './ui';
async function request(path:string,options?:RequestInit){const r=await fetch('/api/vision'+path,options);if(!r.ok){const e=await r.json();throw new Error(e.detail||'视觉请求未完成')}return r.json()}
export default function Vision(){
 const [doctor,setDoctor]=useState<any>(null),[results,setResults]=useState<any[]>([]),[error,setError]=useState(''),[job,setJob]=useState<any>(null),[file,setFile]=useState<File|null>(null),[type,setType]=useState('local'),[device,setDevice]=useState('cuda'),[sourceId,setSourceId]=useState(''),[licence,setLicence]=useState(''),[notes,setNotes]=useState(''),[url,setUrl]=useState(''),[title,setTitle]=useState(''),[event,setEvent]=useState(''),[players,setPlayers]=useState(''),[round,setRound]=useState(''),[quality,setQuality]=useState<any>(null),[elapsed,setElapsed]=useState(0),[busy,setBusy]=useState(false),[professionalMatches,setProfessionalMatches]=useState<any[]>([]),[linkedMatchId,setLinkedMatchId]=useState(''),[rightsConfirmed,setRightsConfirmed]=useState(false),[clipNote,setClipNote]=useState('');
 useEffect(()=>{request('/analyses').then(setResults).catch(e=>setError(String(e)));fetch('/api/professional-matches').then(r=>{if(!r.ok)throw new Error('职业比赛列表暂不可用');return r.json()}).then(setProfessionalMatches).catch(()=>{})},[]);
 useEffect(()=>{if(job?.status!=='running')return;const timer=setInterval(()=>{setElapsed(v=>v+1);request('/jobs/'+job.id).then(j=>{setJob(j);if(j.status==='complete')request('/analyses').then(setResults);if(j.status==='failed')setError(j.error)}).catch(e=>setError(String(e)))},1000);return()=>clearInterval(timer)},[job?.id,job?.status]);
 async function action(fn:()=>Promise<void>){setBusy(true);setError('');try{await fn()}catch(e){setError(String(e))}finally{setBusy(false)}}
 async function importVideo(){if(linkedMatchId){if(!file)throw new Error('请先选择比赛短片');if(!rightsConfirmed)throw new Error('请确认你有权分析这段短片');if(!clipNote.trim())throw new Error('请填写短片来源与授权说明');const data=new FormData();data.append('file',file);data.append('rights_confirmed','true');data.append('source_note',clipNote);data.append('device',device);const result=await request(`/professional-matches/${encodeURIComponent(linkedMatchId)}/balltrack-clip`,{method:'POST',body:data});setJob(result.job);setQuality(result);setElapsed(0);return}const source={type,provider:type==='wtt_licensed'?'WTT Media Archive':'用户提供',rights:type==='wtt_licensed'?'licensed':'user_provided',source_id:sourceId||null,licence_reference:licence||null,rights_notes:notes,original_url:url||null,title,event,players,round};if(type==='external_reference'){await request('/reference',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(source)});setQuality({reference:true});return}if(!file)throw new Error('请先选择本地视频');const data=new FormData();data.append('file',file);data.append('source',JSON.stringify(source));data.append('device',device);const result=await request('/import',{method:'POST',body:data});setJob(result.job);setQuality(result);setElapsed(0)}
 const disabled=busy||job?.status==='running';
 return <><PageHeader title="视频分析 · 实验" text="本机球追踪与真实标注基准。视觉观测不会自动变成技战术结论。"/>{error&&<div role="alert" className="error-banner"><strong>视觉处理未完成</strong><p>{error}</p><p>已有比赛仍可使用。检查模型状态、显卡与日志后重试；无 GPU 时可明确选择 CPU。</p></div>}
 <Card><h2>导入本地视频</h2><p>PTTI 不下载第三方平台视频，不绕过访问权限。仅导入你有权使用的媒体。</p><div className="settings-grid"><label>关联到已登记比赛（可选）<select value={linkedMatchId} onChange={e=>setLinkedMatchId(e.target.value)}><option value="">不关联，作为独立短片分析</option>{professionalMatches.filter(m=>['LOCAL_USER_VIDEO','LICENSED_WTT_LOCAL','RESEARCH_DATASET'].includes(m.video_source_type)&&['USER_AUTHORIZED','LICENSED_FOR_ANALYSIS','RESEARCH_DATASET_AUTHORIZED'].includes(m.rights_status)).map(m=><option key={m.match_id} value={m.match_id}>{m.event_name} · {m.players?.player_a?.canonical_name_zh||m.player_a_id} vs {m.players?.player_b?.canonical_name_zh||m.player_b_id}</option>)}</select></label><label>处理设备<select value={device} onChange={e=>setDevice(e.target.value)}><option value="cuda">NVIDIA GPU</option><option value="cpu">CPU（可能很慢）</option></select></label>{linkedMatchId?<><label>选择比赛短片（最多 60 秒 / 1800 帧）<input type="file" accept=".mp4,.mov,.mkv,.avi" onChange={e=>setFile(e.target.files?.[0]||null)}/></label><label>短片来源与授权说明<textarea value={clipNote} onChange={e=>setClipNote(e.target.value)} placeholder="例如：从本人获授权的本地比赛录像中截取"/></label><label><input type="checkbox" checked={rightsConfirmed} onChange={e=>setRightsConfirmed(e.target.checked)}/> 我有权在本机分析这段短片</label></>:<><label>来源<select value={type} onChange={e=>setType(e.target.value)}><option value="local">本地视频</option><option value="wtt_licensed">已授权 WTT 素材</option><option value="external_reference">外部参考链接（只保存记录）</option></select></label>{type!=='external_reference'?<label>选择视频<input type="file" accept=".mp4,.mov,.mkv,.avi" onChange={e=>setFile(e.target.files?.[0]||null)}/></label>:<label>参考链接<input value={url} onChange={e=>setUrl(e.target.value)}/></label>}<label>标题<input value={title} onChange={e=>setTitle(e.target.value)}/></label><label>赛事<input value={event} onChange={e=>setEvent(e.target.value)}/></label><label>球员<input value={players} onChange={e=>setPlayers(e.target.value)}/></label><label>轮次<input value={round} onChange={e=>setRound(e.target.value)}/></label>{type==='wtt_licensed'&&<><label>素材 / 记录 ID<input value={sourceId} onChange={e=>setSourceId(e.target.value)}/></label><label>授权凭据编号（可选）<input value={licence} onChange={e=>setLicence(e.target.value)}/></label></>}<label>权利 / 来源备注<textarea value={notes} onChange={e=>setNotes(e.target.value)}/></label></>}</div><button className="primary" disabled={disabled} onClick={()=>action(importVideo)}>{linkedMatchId?'分析并关联短片':type==='external_reference'?'保存参考记录':'导入并追踪球'}</button>{quality&&<p>{quality.reference?'参考记录已保存在本机，未下载视频。':`${quality.video.width} × ${quality.video.height} · ${quality.video.fps} FPS · ${quality.video.duration} 秒 · ${quality.video.codec} · 输入分级 ${quality.quality.level}（不保证准确率）`}</p>}</Card>
 {job&&<Card><h2>{job.status==='running'?'正在处理视频':job.status==='complete'?'分析已完成':'处理失败'}</h2><p role="status">{job.stage} · 已等待 {elapsed} 秒</p>{job.status==='running'&&<p>显示当前真实阶段，不提供估算百分比。请保持应用打开。</p>}{job.technical_log&&<p>技术日志：{job.technical_log}</p>}</Card>}
 <Card><h2>研究 / RacketVision Benchmark</h2><p>只运行已安装的官方单回合测试样本。不会静默下载模型或数据。</p><div className="actions"><button disabled={disabled} onClick={()=>action(async()=>setDoctor(await request('/doctor')))}>检查视觉环境与模型</button><button disabled={disabled} onClick={()=>action(async()=>{setJob(await request('/benchmark',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({device})}));setElapsed(0)})}>运行官方小样本基准</button></div>{doctor&&<><p>BallTrack：{doctor.BallTrack} · RacketPose：{doctor.RacketPose} · TrajPred：{doctor.TrajPred}</p><p>GPU 加速：{doctor.worker?.cuda_available?'可用':'不可用 / 未安装'} · 数据集：{doctor.dataset?'已安装':'未安装'}</p><details><summary>环境技术详情</summary><pre>{JSON.stringify(doctor,null,2)}</pre></details></>}</Card>
 <Card><h2>已完成的本地视觉分析</h2>{!results.length&&<p>暂无结果。安装视觉环境后，导入一段短视频或运行小样本基准。</p>}{results.map(r=><section key={r.analysis_id}><h3>{r.source.title||r.source.source_id||r.analysis_id}</h3><p>{r.video.width} × {r.video.height} · {r.video.fps} FPS · {r.video.duration} 秒</p>{r.metrics&&<><p>有标注帧可见召回：{r.metrics.visible_recall==null?'—':(100*r.metrics.visible_recall).toFixed(1)+'%'} · 平均误差：{r.metrics.mean_position_error_px?.toFixed(2)??'—'} px · P95：{r.metrics.p95_position_error_px?.toFixed(2)??'—'} px</p><p>只评价稀疏标注帧。尚无通过阈值，不等于官方全数据集结果。</p></>}<video controls preload="metadata" style={{maxWidth:'100%',maxHeight:420}} src={'/api/vision/analyses/'+r.analysis_id+'/ball_overlay.mp4'}/><div className="actions"><a href={'/api/vision/analyses/'+r.analysis_id+'/analysis.json'} download>导出 JSON</a><a href={'/api/vision/analyses/'+r.analysis_id+'/report.html'} download>导出 HTML</a><a href={'/api/vision/analyses/'+r.analysis_id+'/ball_overlay.mp4'} download>保存轨迹视频</a></div><details><summary>来源与复现信息</summary><pre>{JSON.stringify(r.provenance,null,2)}</pre></details></section>)}</Card></>
}
